### ISSUE TITLE
Azure SQL auditing with input bindings

### ISSUE THREAD

**Issue by NathZ1** [Azure/azure-functions-sql-extension#1086]
- Azure Functions SQL Extension or Extension Bundle Version: 4.*
- Is this a deployed or local function: Deployed
- What type of Database are you using? Microsoft SQL Azure (RTM) - 12.0.2000.8 , EngineEdition = 5
- List any custom settings for your function app: None

I have been using SQL Bindings for my Functions app for a while with no complaints. I now have to implement SQL Database auditing but am struggling with creating accurate audit records. 

The core issue is that when the function is triggered the input binding immediately gets the required data, before authentication of the user has occurred. I do auth checks within the function body, then conditionally either return the SQL data (if user is authenticated), or a 403 error (if they are not authenticated). This will theoretically result in audit logs being created that describe a user accessing data, when they may not actually receive the data (if failed authentication). 

What is the preferred pattern to ensure that auditing records are correct?

**Comment by JetterMcTedder** [comment]
@NathZ1 You are correct, when using a function, connection to the database will be handled by what is in the settings parameter and not have that user login. You are also correct with having a pre-check in the function to handle the auth. The auth/403 audit logs could be useful in seeing who is accessing and who is trying to access the data so that could be a positive here.

**Comment by Charles-Gagnon** [comment]
To follow up with what @JetterMcTedder said - the pattern you might want to look at is using [Imperative (Runtime) Bindings](https://learn.microsoft.com/azure/azure-functions/functions-bindings-expressions-patterns#binding-at-runtime)

You can see a sample here : https://github.com/Azure-Samples/azure-sql-blazor-tag-game-sample/blob/main/APIs/GetUserInfo.cs

**Comment by NathZ1** [comment]
Thanks for the replies. 

Runtime bindings would likely solve the issue - they would also solve the prior issue I had along the same lines where stored procs or anything that triggers a DB change (like DELETE) would occur prior to authentication within the function code, requiring doing the auth check within a function without bindings, then calling a secondary function after the auth check returns (with the second function having the bindings that perform the DB changes) (existing issue in the backlog tracking this that's been there a while - https://github.com/Azure/azure-functions-sql-extension/issues/605).

However....... all of my Function apps are written in TypeScript (as they are part of a larger production React.js web application also written in TypeScript). It would be a large shift to re-write all the Function code into C#, and would require additional development  resources skilled in C# since we don't have a lot of expertise in our existing team currently. 

@Charles-Gagnon - Ignoring technical difficulty and time required to implement, would it be theoretically possible to implement runtime bindings for Node based Function apps coded in JavaScript/TypeScript? I feel that this would provide so much more flexibility having this functionality - it would fix the messy requirement of having functions calling other functions to prevent binding executing immediately as well.

The way I see it currently, my only options with the current state are:
1) Re-write entire function apps to C# to use imperative binding - Very large time commitment required to re-write all functions, additional technical resources required, $$$
2) Stop using SQL Extension altogether and make DB calls directly within function code - Very large time commitment required to re-write all functions, need to handle retries, caching etc, $$$
3) Implement SQL auditing but need to acknowledge that some logs may not be 'true' logs, as although the data went from DB to Function app, it was not returned to the user in the response if they were not authenticated - Unsure whether this would be acceptable from a business perspective

None of these are particularly attractive options!

**Comment by NathZ1** [comment]
I thought about that, but is having 2 functions for every single endpoint really a valid solution? 

Looks like the linked issue has been on the backlog for 4years. Not sure why it hasn't been prioritised as it would make this extension so much more usable.

I think there should be an additional limitation added to the documentation that describes this scenario. It would have been very helpful to know that I have to implement Functiond App with C# if SQL binding are used, as any other language has significant limitations (forcing having to use 2 function calls whenever there os conditional logic in the function body).

**Comment by Charles-Gagnon** [comment]
It's definitely not ideal, but unfortunately there's little that we as a binding extension can do to affect that directly. I'd definitely encourage you to upvote & post on the linked issue since I agree that would be very useful functionality to have.

We'll look into making these kinds of limitations clearer in our documentation though - but for now is there anything else you need or can we close this issue since there's nothing actionable we can do directly on our end?

**Comment by NathZ1** [comment]
Happy for it to be closed, unless you would like to leave it open to help track and documentation changes.

**Comment by NathZ1** [comment]
Sorry @JetterMcTedder and @Charles-Gagnon , I have just come across this: https://techcommunity.microsoft.com/t5/apps-on-azure-blog/azure-functions-node-js-v4-programming-model-is-generally/ba-p/3929217.

It seems that the [Azure Functions Node.js worker](https://github.com/Azure/azure-functions-nodejs-worker) has reached v4 of its programming model. Hightlights of v4 are flexible folder structure and 'define function in code' which to me sounds exactly like imperative bindings... is that correct?

**Comment by NathZ1** [comment]
https://github.com/Azure/azure-functions-nodejs-library/issues/88

looks like there is already support for SQL bindings with v4 model, but no documentation on how to use it?

**Comment by NathZ1** [comment]
I just spent some time implementing the v4 model, but the issue remains unfortunately. Even when i use the bindings within the function code conditionally, it is still triggered regardless :(

```
const userAuth = await isUserAuth(request.headers.get('token') || '', request.query.get('group'), false)

//I thought that this should only execute the input binding when userAuth === true, but it triggers immediately :(
if (userAuth) context.extraInputs.get(sqlInput)
```

**Comment by Charles-Gagnon** [comment]
Yeah - we have a backlog task to update our setup guide for the v4 model : https://github.com/Azure/azure-functions-sql-extension/issues/1017

But as you found out, that unfortunately won't help in this situation. The core implementation of Azure functions is the issue here - a binding is executed as soon as the function is triggered regardless for all non-C# languages. The support for that is something that would need to be added to the Host first.
