### ISSUE TITLE
BuildRenewLeasesCommand Should Not Generate Invalid T-SQL with Empty WHERE Clauses

### ISSUE THREAD

**Issue by chlafreniere** [Azure/azure-functions-sql-extension#1093]
Customer has reported that the SQL Trigger will occasionally try to send T-SQL from https://github.com/Azure/azure-functions-sql-extension/blob/80172755025ea5584985e8a5274a9035f08b80dc/src/TriggerBinding/SqlTableChangeMonitor.cs#L953 with empty `WHERE` clauses, which causes SQL failures. Although further retries to build renew lease commands succeed, we should, at a minimum, check that `matchCondition` is not an empty string before building the T-SQL.

**Comment by MaddyDev** [comment]
Added a work around https://github.com/Azure/azure-functions-sql-extension/issues/1108
