### ISSUE TITLE
Using headers within commandText is prone to SQL Injection attack

### ISSUE THREAD

**Issue by NathZ1** [Azure/azure-functions-sql-extension#1094]
I am trying to pass information from HTTP Trigger request header into the SQL Input binding. I can't use connection parameters as it only includes values from params. When testing this pattern I noticed this can result in SQL Injection attack. Can this data be cleansed to prevent SQL injection attack, or alternatively can the parameters logic be modified to include header properties for use?

The background - 
I want to pass user information through a header, which is then added to the SQL command as a comment. This is for SQL DB auditing purposes, so it logs the actual user that is accessing the data (since the DB connection is the Function App itself). 

The bigger picture is that Azure Functions don't really properly support Azure SQL Auditing. I have a strict business requirement that db data is audited. Azure Functions are heading in the direction of data bindings, and managed identity for connection to DBs, with no documented patterns for how to facilitate database auditing. Yes I could use an SDK instead of SQL bindings, but this adds a heap of complexity to the point where I may as well create a traditional API using Node/Express.js or something similar, rather than using a Function App for API. 

Steps to Reproduce:

function.json:
```
{
  "bindings": [
    {
      "name": "req",
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "methods": [
        "get"
      ]
    },
    {
      "name": "res",
      "type": "http",
      "direction": "out"
    },
    {
      "name": "sqlData",
      "type": "sql",
      "direction": "in",
      "commandText": "SELECT * FROM dbo.tableTest --{headers.userInfoStr}",
      "commandType": "Text",
      "connectionStringSetting": "SqlConnectionString"
    }
  ],
  "scriptFile": "../dist/test/index.js"
}
```
Note: using this example, i don't think you can terminate the single line comment, which would be required for SQL Injection attack. However, if somebody wanted to use a header property for a different reason within the command, it is definitely possible. eg -

`"commandText": "SELECT * FROM dbo.table WHERE tableColumn = {headers.user}"`

with headers.user set to "1 or 1=1;DELETE FROM otherTable" or something similar...

**Comment by JetterMcTedder** [comment]
To start, I dont think it would be wise to just have header info inserted/appended into SQL like this. Its no so much a sql injection but an incorrect pattern. If you wanted user info, and are using static web apps for auth, there are ways of getting user info from the claims variables built into Azure functions. You would also probably want to use another output function to log user activity.

All in all, never blindly append header info (or any un-sanitized strings) to a SQL statement. Also, if using static web apps for auth, use the built in methods for getting logged in user info.
