### ISSUE TITLE
 Core Microsoft SqlClient Data Provider: Line 1: Length or precision specification 0 is invalid

### ISSUE THREAD

**Issue by kannanMSFT** [Azure/azure-functions-sql-extension#110]
#### Azure SQL Table Schema:

```sql
create table Metrics (
	MessageId varchar(64) NOT NULL PRIMARY KEY,
	CreatedDate date NOT NULL,
	DeliveryDurationMs NUMERIC(10,7) not null
)
```
Model on C# side:

```csharp
    public class Metric
    {
        public string MessageId {get;set;}
        public string CreatedDate {get; set;}
        public double DeliveryDurationMs {get;set;}
    }
```
Azure function output binding for adding a single row to SQL table, based on service bus queue trigger.

```csharp
//....
[Sql("Metrics", ConnectionStringSetting = "sqlconnection")] out Metric metric,
 ILogger log)
{
    //....
    //...
    //...

    var diff = enqueuedTimeUtc - creationTime;

    metric = new Metric
            {
                MessageId = messageId,
                Date = enqueuedTimeUtc.ToString("yyyy-MM-dd"),
                DeliveryDurationMs = diff.TotalMilliseconds
            };
```

#### Azure function reports the following error:

System.Private.CoreLib: Exception while executing function: perfreportapp. Microsoft.Azure.WebJobs.Host: Error while handling parameter metric after function returned:. Core Microsoft SqlClient Data Provider: Line 1: Length or precision specification 0 is invalid.

#### Question:

Not sure if this a bug or I am doing something incorrect. Let me know.

**Comment by chlafreniere** [comment]
Hi @kannanMSFT we've fixed this in https://github.com/Azure/azure-functions-sql-extension/pull/68 and will be available when we push our bits to NuGet. If you're consuming bits via myget, we do not plan on updating that package in the future.

If you have any questions on release logistics, please feel free to email me. Thanks!
