### ISSUE TITLE
Docs still mention old way Function ID is generated

### ISSUE THREAD

**Issue by Charles-Gagnon** [Azure/azure-functions-sql-extension#1107]
The docs here still mentioned the function ID being made from the HostID + class/method name, which isn't accurate anymore after https://github.com/Azure/azure-functions-sql-extension/pull/1071

https://github.com/Azure/azure-functions-sql-extension/blob/main/docs/TriggerBinding.md#az_funcleasestablename

There may be other places in the docs this is mentioned as well, we should ensure that everything is updated with the latest state to avoid confusion.

**Comment by Charles-Gagnon** [comment]
@MaddyDev Assigning this to you as follow up to your PR

**Comment by MaddyDev** [comment]
Fixed https://github.com/Azure/azure-functions-sql-extension/pull/1109
