### ISSUE TITLE
Function App with an SQL trigger has unexpectedly stopped

### ISSUE THREAD

**Issue by abyahia** [Azure/azure-functions-sql-extension#1150]
- Azure Functions SQL Extension or Extension Bundle Version: 4
- Is this a deployed or local function: deployed function
- What type of Database are you using? (Run `SELECT @@VERSION as Version, SERVERPROPERTY('EngineEdition') as EngineEdition` on your database) : Microsoft SQL Azure (RTM) - 12.0.2000.8  	Oct  2 2024 11:51:41  	Copyright (C) 2022 Microsoft Corporation 
- List any custom settings for your function app. This could be a custom time-out defined specifically for your database server or optional configuration that can be customized for the app defined [here](https://learn.microsoft.com/azure/azure-functions/functions-bindings-azure-sql-trigger?tabs=isolated-process%2Cportal&pivots=programming-language-csharp#optional-configuration).

Steps to Reproduce:

I have a Function App with an SQL trigger deployed in a development environment using the B3 hosting plan. I've noticed that the function stops unexpectedly multiple times, but it resumes working when I restart it manually. In contrast, the same Function App deployed in the production environment using the P0V3 hosting plan has never experienced interruptions. Could you explain the possible reasons for this behavior?

Thank you.

**Comment by Charles-Gagnon** [comment]
What [hosting plan](https://learn.microsoft.com/en-us/azure/azure-functions/functions-scale) do you have for each instance?

**Comment by abyahia** [comment]
For development I have Basic B3 Hosting plan and for production Premium v3 P0V3.

**Comment by Charles-Gagnon** [comment]
Do you have autoscale enabled for these? And if so - what is the minimum instance limit you have configured?

https://learn.microsoft.com/en-us/azure/azure-monitor/autoscale/autoscale-get-started

**Comment by abyahia** [comment]
No, I don't have autoscale enabled.

**Comment by Charles-Gagnon** [comment]
And are there any errors in the logs? We're not aware of any issues aside from autoscaling that could cause this - so we'll need some more info to help.

**Comment by abyahia** [comment]
There is no errors in the logs as the function is stopped by itself.

**Comment by Charles-Gagnon** [comment]
Unfortunately if there aren't any errors in the logs there isn't much we can tell from our side. Perhaps you could open an issue in https://github.com/Azure/azure-functions-host/tree/dev to see if they might be able to track down why the function would be stopping? Our extension doesn't directly control anything about that.

I'm going to close this for now since there isn't anything actionable we can do - but if you get more information please respond here and we'll help out if we can!
