### ISSUE TITLE
Polling Period - Exponential Backoff

### ISSUE THREAD

**Issue by sophiatev** [Azure/azure-functions-sql-extension#12]
Right now, our period for polling for changes is a hard-coded value of 10 seconds. It might make sense to change this to exponential back-off for more responsiveness/a more efficient use of resources ([example](https://github.com/Azure/azure-webjobs-sdk/blob/9be0dcb611674ebab5415bc0726040050e6c0260/src/Microsoft.Azure.WebJobs.Extensions.Storage/Queues/Listeners/QueueListener.cs#L125) of how the Queue binding does it).

**Comment by dzsquared** [comment]
Closing as it is related to archived trigger code
