### ISSUE TITLE
Publish NuGet package

### ISSUE THREAD

**Issue by chlafreniere** [Azure/azure-functions-sql-extension#136]

**Comment by dzsquared** [comment]
probably can close this now?

I noticed that we published a GH release for the x129 initial release, but the next x131 didn't make it on the GH releases.  Not sure we need to keep updating here on GH with the releases, but it could be a good place to keep release notes.

**Comment by Charles-Gagnon** [comment]
Oops, yeah thanks for the reminder. I'll add the new release as well, it's something we need to improve for sure. I'll see about adding that to the pipeline
