### ISSUE TITLE
Failing All Rows in a Batch

### ISSUE THREAD

**Issue by sophiatev** [Azure/azure-functions-sql-extension#14]
Right now, the trigger binding code will effectively "fail" all change table rows part of a batch that a worker is processing even if only some of them were processed unsuccessfully. Failing involves stopping renewal of leases on the rows, but also not releasing the leases. This means another worker will acquire leases on the rows and try processing them. For the actually failed rows, this is the expected behavior. For the other rows in the batch, we end up re-processing rows that were actually processed successfully. A better way to do this would be to have the worker determine which rows were actually successfully processed in the batch, and trigger the function on those, afterwards releasing the lease on them. For the unsuccessfully processed rows, it should stop renewal of leases but also not release the leases so that another worker tries to process them. (Current code for how this is handled [here](https://github.com/Azure/azure-functions-sql-extension/blob/dev/src/SqlBinding/TriggerBinding/SqlTableWatcher.cs#L222)).

**Comment by Charles-Gagnon** [comment]
Closing trigger binding related issues until we revisit support for that
