### ISSUE TITLE
Deadlocks in the Trigger Binding

### ISSUE THREAD

**Issue by sophiatev** [Azure/azure-functions-sql-extension#16]
In the current implementation of the `SqlTableWatcher`, the methods that [acquire leases ](https://github.com/Azure/azure-functions-sql-extension/blob/dev/src/SqlBinding/TriggerBinding/SqlTableWatcher.cs#L354)and [release leases](https://github.com/Azure/azure-functions-sql-extension/blob/dev/src/SqlBinding/TriggerBinding/SqlTableWatcher.cs#L452) on change table rows use the Repeatable Read transaction level. The Repeatable Read and Serializable transaction levels both ensure that read locks are held throughout the entire transaction, which is functionality we need (see Steps of Operation, steps 1 and 6, for an explanation as to why in this [design doc](https://microsoft-my.sharepoint.com/:w:/p/t-sotevo/EQdANWq9ZWpKm8e48TdzUwcBGZW07vJmLf8TL_rtEG8ixQ?e=9Fj89Q)).
If we have a lot of concurrency, deadlocks could be quite common. In fact, even with just two workers running for a few hours, deadlocks happened at least twice. It's worth considering alternatives to the current design that are less deadlock-prone.

**Comment by Charles-Gagnon** [comment]
Closing trigger binding related issues until we revisit support for that
