### ISSUE TITLE
[Language Support] Powershell

### ISSUE THREAD

**Issue by brettmillerb** [Azure/azure-functions-sql-extension#163]
Currently to perform SQL tasks within Azure functions and PowerShell I have been using the SQLServer module as a requirement but would prefer native binding functionality if it's at all possible.

**Comment by dzsquared** [comment]
@brettmillerb  - which of the cmdlets from the SQLServer module are you using currently?  are the SQL tasks you're using functions for administrative actions?

**Comment by brettmillerb** [comment]
> @brettmillerb - which of the cmdlets from the SQLServer module are you using currently? are the SQL tasks you're using functions for administrative actions?

Hi @dzsquared this was predominently for `Invoke-SqlCmd` and `SELECT`, `UPDATE` & `INSERT` statements. I envisioned it working similar to the table storage binding where you can specify the filter in the binding and parameterise the route etc.

Since the PowerShell `Push-OutputBinding` serialises JSON `UPDATE` statements would be as easy as just outputting a `pscustomobject`

At present I am shipping the SqlServer module in the requirements.psd1 with the function and manageddependencies enabled and then writing SQL queries as strings within the functions etc.

**Comment by VasuBhog** [comment]
Hello @brettmillerb, we full support Azure Functions with SQL Bindings using PowerShell. Feel free to look at the samples located [here](https://github.com/Azure/azure-functions-sql-extension/tree/main/samples/samples-powershell) and let me know if you have further questions about the support you are looking for.
