### ISSUE TITLE
Function trigger support

### ISSUE THREAD

**Issue by dzsquared** [Azure/azure-functions-sql-extension#166]
In addition to input/output bindings, it would be helpful to be able to trigger a function based on changes in a table

**Comment by jmarbutt** [comment]
I feel like I have asked for this in the past on other Microsoft feedback sites, so this has been requested before this repo was created.

**Comment by dzsquared** [comment]
hi @jmarbutt! I apologize if it seems your previous feedback was lost in other places before the SQL bindings library repo was opened up. Since you've been needing/considering the trigger from SQL to function architecture for a while, curious about the alternative designs you've used or considered in creating your apps.

**Comment by jmarbutt** [comment]
@dzsquared I have looked at using Hasura and swapping to Postgres as an option. Their implementation is pretty decent and they are working towards a SQL Server implementation. It is perfect on Postgres, looking for something similar in the azure/sql server world.

**Comment by ilmax** [comment]
@dzsquared I'm very interested in this one, do you have a design document I can read up to see if this can cover my use case?

**Comment by dzsquared** [comment]
Trigger support is now available in public preview for C# functions: https://learn.microsoft.com/azure/azure-functions/functions-bindings-azure-sql-trigger
