### ISSUE TITLE
Release build patch # won't reset correctly when major version is bumped

### ISSUE THREAD

**Issue by zijchen** [Azure/azure-functions-sql-extension#173]
https://github.com/Azure/azure-functions-sql-extension/blob/dc04f21cea20d5792fa939b65fcf30e06a2da43b/builds/azure-pipelines/build-release.yml#L18

I realized this issue when setting up a pipeline for DacFx. Right now the counter is only on versionMinor which is fine until you increment versionMajor and reset versionMinor back to a lower number. The counter will pick up where it left off for that minor version.

For example if the last build for 0.1.x is 100, the first build for 1.1.x will be 101.

In my pipeline I just introduced a new variable that includes both major and minor versions: 
https://github.com/microsoft/DacFx/blob/3ab43f32b4cf515c51a34229bd7ceebf06a966da/builds/build-release.yml#L12

This won't be an issue in the near term, and since you already released I don't think it's worth fixing until the next time you bump the version number. Just raising this issue to prevent future frustrations 😄

**Comment by Charles-Gagnon** [comment]
At some point it would be nice to see about better ways to deal with versioning - there has to be a cleaner way...but for now this is fine. Thanks for the investigation and fix suggestion @zijchen !
