### ISSUE TITLE
Deleting Worker Tables

### ISSUE THREAD

**Issue by sophiatev** [Azure/azure-functions-sql-extension#19]
We need to implement a cleanup task that periodically checks that the user tables associated with worker tables still exist. If ‘Employees’ has been deleted, for example, we should delete the corresponding Worker_Table_Employees and remove its row from the Global_State_Table. (Worker_Table_Employees will actually have the name Worker_Table_{table_id}, where {table_id} = OBJECT_ID('Employees', 'U')).

**Comment by Charles-Gagnon** [comment]
Closing trigger binding related issues until we revisit support for that
