### ISSUE TITLE
Add support for app settings binding expressions

### ISSUE THREAD

**Issue by Saroj-kr** [Azure/azure-functions-sql-extension#200]
Can you please add support for binding expression in SQL command text

**Comment by Saroj-kr** [comment]
Hi Charles,

We have binding expression support for Triggers and Bindings, where we can specify an app setting name within %% to use it directly in expressions.

Here is Microsoft's link for the same:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-expressions-patterns#binding-expressions---app-settings

Azure Function code could be :
`public static async Task<IActionResult> Run(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = "employees")] HttpRequest req,
    ILogger log,
    [Sql("%SP_GetEmployee%",
    CommandType = System.Data.CommandType.StoredProcedure,
    ConnectionStringSetting = "SqlConnectionString")]
    IEnumerable<Employee> employee)
{
    return new OkObjectResult(employee);
}`

And app setting can be:
`"SqlConnectionString": "{connection_string}"
"SP_GetEmployee":"{Stored_Procedure_name}"`

**Comment by Charles-Gagnon** [comment]
Gotcha, definitely seems like a nice feature to have!

More info : https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-expressions-patterns#binding-expressions---app-settings

**Comment by MaddyDev** [comment]
@Saroj-kr Latest package supports this now, thanks.
