### ISSUE TITLE
Support Azure Function C# Script(CSX)  binding

### ISSUE THREAD

**Issue by lshen168** [Azure/azure-functions-sql-extension#218]
Hi, there:
      We tried to use Azure function SQL extension for Azure Function C# script binding, but it doesn't work after many attempts. Below is what we have done:
    Please add sql extension support for Azure Function C# Script(CSX).
    Thanks,

Li

1. Add Microsoft.Azure.WebJobs.Extensions.Sql into function.proj and got the error - see below:

![image](https://user-images.githubusercontent.com/49541834/160939175-7885bc41-9542-4d39-9f66-fe3a0723d02f.png)

2. Try to add SQL binding into function.json - there is no document of how to add them, we added them by referencing to event hub binding - azure function gives no logs and nothing works, our understanding is if the function.json has some error, function host will not work:
   {
      "name": "outputData",
      "direction": "out",
      "type": "SQL",
      "connectionStringSetting": "SQLConnectionString",
      "sqlServerName": "odpsqlserver",
      "databaseName": "ODPUserDB"
    }

**Comment by MaddyDev** [comment]
We're not part of extension bundle yet, but we're part of extension bundle preview, Can you try updating the host.json with the below and try:
"extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle.Preview",
    "version": "[3.*, 4.0.0)"
  }
