### ISSUE TITLE
SQL output binding not working.

### ISSUE THREAD

**Issue by Ansiem** [Azure/azure-functions-sql-extension#236]
Hi there,

I'm currently trying to use the SQL output binding as shown in the example which doesn't seem to work due to an error.
I'm getting the following error message:

The 'Function2' function is in error: Unable to configure binding 'output' of type 'sql'. This may indicate invalid function.json properties. Can not convert Null to Int32.

```csharp
using System;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System.Collections.Generic;
using MetaRijk.Company.Function;

namespace MetaRijk
{
    public static class Function2
    {
        [FunctionName("Function2")]
        public static IActionResult Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "addemployees-array")]
            HttpRequest req, ILogger log,
            [Sql("Employees",
            ConnectionStringSetting = "SqlConnectionString")]
            out Employee[] output)
        {
            output = new Employee[]
                {
            new Employee
            {
                EmployeeId = 1,
                FirstName = "Hello",
                LastName = "World",
                Company = "Microsoft",
                Team = "Functions"
            },
            new Employee
            {
                EmployeeId = 2,
                FirstName = "Hi",
                LastName = "SQLupdate",
                Company = "Microsoft",
                Team = "Functions"
            },
                };

            return new CreatedResult($"/api/addemployees-array", output);
        }
    }

    namespace Company.Function
    {
        public class Employee
        {
            public int EmployeeId { get; set; }
            public string LastName { get; set; }
            public string FirstName { get; set; }
            public string Company { get; set; }
            public string Team { get; set; }
        }
    }
}

```

Hope someone knows how to resolve this issue.

**Comment by Charles-Gagnon** [comment]
Can you run the function with `func start --verbose` and then include the entire error log?

**Comment by Charles-Gagnon** [comment]
And if possible if you could delete any personal information (such as the connection string) and then zip up the project and attach it that would be very helpful.

**Comment by Ansiem** [comment]
> And if possible if you could delete any personal information (such as the connection string) and then zip up the project and attach it that would be very helpful.

When trying to upload the .zip file im getting the error: "Not in list"

**Comment by Charles-Gagnon** [comment]
> > And if possible if you could delete any personal information (such as the connection string) and then zip up the project and attach it that would be very helpful.
> 
> When trying to upload the .zip file im getting the error: "Is not included in the list"

Odd - seems like there's some weirdness with some file uploads, this might be a size thing though. Can you try e-mailing it to me chgagnon@microsoft.com?

**Comment by Ansiem** [comment]
> > > And if possible if you could delete any personal information (such as the connection string) and then zip up the project and attach it that would be very helpful.
> > 
> > 
> > When trying to upload the .zip file im getting the error: "Is not included in the list"
> 
> Odd - seems like there's some weirdness with some file uploads, this might be a size thing though. Can you try e-mailing it to me [chgagnon@microsoft.com](mailto:chgagnon@microsoft.com)?

I tried mailing you but I am getting an e-mail back saying my mail is blocked do your company policy. I've uploaded the zip, it contains another 7zipped file due to file size.
[MetaRijk.zip](https://github.com/Azure/azure-functions-sql-extension/files/8636031/MetaRijk.zip)

**Comment by Charles-Gagnon** [comment]
Alright, so the issue is due to the version of `Microsoft.NET.Sdk.Functions` you're using. Something changed starting with v3.1 that's breaking us. If you revert back to a 3.0.x version (such as 3.0.13) then things seem to work fine.

I'll open a separate issue to track fixing that to keep things clean - let me know if that doesn't resolve the issue for you!

**Comment by Charles-Gagnon** [comment]
Actually - it looks like you can also fix this by adding the "CommandType" parameter to the attribute. No need to revert the version of the package in that case.

```csharp
[Sql("dbo.Employees",
CommandType = System.Data.CommandType.Text,
ConnectionStringSetting = "SqlConnectionString")
```
