### ISSUE TITLE
Python Support - Current State

### ISSUE THREAD

**Issue by Charles-Gagnon** [Azure/azure-functions-sql-extension#250]
Currently Python support for Azure Functions with SQL Bindings is in early preview and requires some additional setup steps to work correctly. 

**IMPORTANT** Support for durable functions is not available in this release. A future release will combine SQL bindings and durable functions capabilities.

## Local Dev Environment

1. Download Azure Function Core Tools (version >= 4.0.4653)
2. Change the bundle name in `host.json` to `Microsoft.Azure.Functions.ExtensionBundle.Preview` and the version to `[4.*, 5.0.0)`
4. Add an app setting named `PYTHON_ISOLATE_WORKER_DEPENDENCIES` and set the value to `1` (to ensure that the correct version of the azure-functions library is used)

## Deployed App

1. Ensure that the host.json of the deployed app specifies the `Microsoft.Azure.Functions.ExtensionBundle.Preview` bundle with version `[4.*, 5.0.0)`
3. Add an app setting named `PYTHON_ISOLATE_WORKER_DEPENDENCIES` and set the value to `1` (to ensure that the correct version of the azure-functions library is used)

**Comment by lucyzhang929** [comment]
Closing this issue since we no longer need to set the `PYTHON_ISOLATE_WORKER_DEPENDENCIES` flag with the [latest core tools version v.4.0.5030](https://github.com/Azure/azure-functions-core-tools/releases/tag/4.0.5030).
