### ISSUE TITLE
CommandTimeout

### ISSUE THREAD

**Issue by roberto-mardeni** [Azure/azure-functions-sql-extension#258]
Add support to override command timeout for queries

**Comment by dzsquared** [comment]
@roberto-mardeni SQL bindings uses Microsoft.Data.SqlClient, so you can set the command timeout property in the connection string you provide in app settings.

introduced to sqlclient back in 2.1: https://github.com/dotnet/SqlClient/pull/722
https://docs.microsoft.com/dotnet/api/microsoft.data.sqlclient.sqlconnection?view=sqlclient-dotnet-core-3.1

**Comment by dzsquared** [comment]
I'm going to close this item - we have additional notes on this about to be published in the docs. Let me know if anything else comes up!
