### ISSUE TITLE
How to pass query parameter by using queue binding

### ISSUE THREAD

**Issue by kenakamu** [Azure/azure-functions-sql-extension#261]
I know http trigger can pass parameter as Query.[attr], but I use queue trigger.

I declare class for queue object, but i cannot use query trigger binding parameter as Parameter= in Sql attribute.

**Comment by Charles-Gagnon** [comment]
Can you provide an example of the code you expect to work and what you expect to happen?

**Comment by chaudhry13** [comment]
I am also wondering, does SQL bindings work with Service Bus Queue trigger? If yes, is there any example?

**Comment by Charles-Gagnon** [comment]
We don't have an example but it should work fine - we have a sample for a normal Queue trigger here https://github.com/Azure/azure-functions-sql-extension/blob/main/samples/samples-csharp/OutputBindingSamples/QueueTriggerProducts.cs

**Comment by Charles-Gagnon** [comment]
Closing since there hasn't been any response, if you can provide more details about what behavior you'd like to see we can investigate and reopen if needed. Thanks!
