### ISSUE TITLE
Tracking bug in microsoft.net.sdk.functions >=4.1.0

### ISSUE THREAD

**Issue by dzsquared** [Azure/azure-functions-sql-extension#263]
A bug exists in Microsoft.NET.Sdk.Functions starting with 4.1.0 (4.1.1 currently), where a function utilizing SQL output bindings will fail to start unless an additional `CommandType = CommandType.TableDirect` is added to the definition.

This issue is for tracking the correction of the issue.

Temporary work arounds:
1. Downgrade to `<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.0.1" />`
2. Add `CommandType = CommandType.TableDirect` to SQL output bindings

**Comment by Charles-Gagnon** [comment]
Oh hey that's right, I actually already had a bug submitted about this. I just forgot the context.

https://github.com/Azure/azure-functions-sql-extension/issues/237

@dzsquared I'm going to close the other one, but make sure they know that it's breaking for v3 of the function runtime as well
