### ISSUE TITLE
Create an automated build validation workflow

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-sql-extension#3]
In order to validate that the build and unit tests continue to stay healthy, we'll want to build a CI for this repo that runs automatically for every PR that gets opened. I recommend we use GitHub Actions for this. I recently created a GitHub Actions CI for another SQL project which you can use as a reference (you might even be able to just copy it and change some file paths): https://github.com/cgillum/durabletask-sqlserver/blob/main/.github/workflows/build-and-test.yml

**Comment by zijchen** [comment]
I set up an Azure pipeline for validation and build in this PR: https://github.com/Azure/azure-functions-sql-extension/pull/45
We opted for ADO as Github Actions doesn't have all the functionalities we need yet (e.g. Code Signing)
