### ISSUE TITLE
Check if passing of cancellation token to `SqlTableChangeMonitor` class makes sense

### ISSUE THREAD

**Issue by JatinSanghvi** [Azure/azure-functions-sql-extension#307]
This issue tracks the fix to address the code review comment in #226.

This seems like something we should be doing

_Originally posted by @Charles-Gagnon in https://github.com/Azure/azure-functions-sql-extension/pull/226#discussion_r932380333_

**Comment by AmeyaRele** [comment]
Looked into this, with reference to other extensions.
The CancellationToken in StartAsync method is limited to that method in all of the extensions. [TimerTrigger](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/87d0c9888d7c6ebb9816285c8ece27f1b7095c30/src/WebJobs.Extensions/Extensions/Timers/Listener/TimerListener.cs#L83), [CosmosDBTrigger](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/48f50ce73e5f520938f58d08933bb691c9d16329/src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerListener.cs#L90)
The cancellation token used during actual execution is always a different one.
In [SqlTableChangeMonitor](https://github.com/Azure/azure-functions-sql-extension/blob/triggerbindings/src/TriggerBinding/SqlTableChangeMonitor.cs) there are 3 cancellationTokenSource instantiated. One for RunChangeConsumptionLoopAsync, RunLeaseRenewalLoopAsync and for function executor.

Also, none of the calls made in SqlTableChangeMonitor constructor uses CancellationToken. Based on this the CancellationToken does not need to be passed to SqlTableChangeMonitor. Discussed this with @JatinSanghvi as well.

Would be happy to hear your thoughts @Charles-Gagnon.

**Comment by Charles-Gagnon** [comment]
Gotcha, yeah that makes sense. Looks like we're handling the StopAsync stuff correctly too - although if you could make sure you go through and look at that it'd be good to have some more eyes verifying that all the connections are being closed properly. 

One thing that would be nice is to update https://github.com/Azure/azure-functions-sql-extension/blob/8c01883733d700b11551ff1f956fee8f017df1e9/src/TriggerBinding/SqlTableChangeMonitor.cs#L159 to have a comment saying that the lease renewal loop will be stopped once the CheckForChanges loop finishes. (It might be cleaner to cancel both there instead, but not something I see as a huge problem)

**Comment by AmeyaRele** [comment]
> One thing that would be nice is to update
> 
> https://github.com/Azure/azure-functions-sql-extension/blob/8c01883733d700b11551ff1f956fee8f017df1e9/src/TriggerBinding/SqlTableChangeMonitor.cs#L159
> 
> to have a comment saying that the lease renewal loop will be stopped once the CheckForChanges loop finishes. (It might be cleaner to cancel both there instead, but not something I see as a huge problem) just to make sure anyone looking at the code isn't confused about why we only cancel one of the sources.

Created PR for this, closing the issue.
