### ISSUE TITLE
Clarify requirements around ConnectionStringSetting and CommandType properties of SqlBinding

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-sql-extension#31]
### Issue
I tried to use the SQL binding without explicitly setting a connection string setting name since it is an optional.

```csharp
[FunctionName("Function1")]
public static async Task<IActionResult> Run(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
    [Sql("SELECT * FROM dt.Instances")] IEnumerable<JObject> instances,
    ILogger log)
{
    log.LogInformation("C# HTTP trigger function processed a request.");
    return new OkObjectResult(instances);
}
```

The code compiles fine, but when I ran the function, it failed with the following error message:

> [2020-10-16T21:22:08.482] System.Private.CoreLib: Exception while executing function: Function1. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'instances'. SqlBinding: Must specify ConnectionStringSetting, which should refer to the name of an app setting that contains a SQL connection string.

### Expected
I would have expected it to do one of the following:

1. Look for a default app setting name, like `SqlConnectionString` and then tell me explicitly to add that as an app setting, or...
2. Fail to compile - i.e. the `ConnectionStringSetting` should be a required parameter of the `[SqlBinding]` attribute.

This is a corner-case issue about better error handling. Obviously this wouldn't be an issue for anyone following the directions, but it's good to help ensure that folks don't accidentally get into a bad place.

**Comment by cgillum** [comment]
Similar problem with the `CommandType` property. In that case, I would have expected to it default to `CommandType.Text` if I don't specify anything.

**Comment by MaddyDev** [comment]
> @MaddyDev FYI I started looking at this over the weekend since I think it's something we should look at doing sooner rather than later. Let me know if you were planning on doing anything here this yourself soon otherwise I plan on having something out for this this week.
> 
> @chlafreniere @dzsquared FYI

I haven't started on this yet, currently working on other issues that are in GA milestone, you can take a dive at it this week if you have time.
