### ISSUE TITLE
Move README content into wiki

### ISSUE THREAD

**Issue by Charles-Gagnon** [Azure/azure-functions-sql-extension#313]
The README is getting extremely large and hard to navigate. It would be better to move the content into the wiki and have the README just be a brief overview of the extension instead of a full rundown of how to use it.

**Comment by Charles-Gagnon** [comment]
- Moving this into trigger public preview milestone since that'll be a good time to get this cleaned up. @dzsquared I'll work with you to get this done, likely right after we merge the trigger branch into main.

**Comment by dzsquared** [comment]
alternative implementation suggestion - 'docs' folder with markdown files (or similar) instead of the wiki
