### ISSUE TITLE
Error message for output binding doesn't explain the issue when table name is wrong

### ISSUE THREAD

**Issue by jwendl** [Azure/azure-functions-sql-extension#32]
### Description
When pointing the binding to a table that isn't valid it gives an error message saying it can't find the primary key, when the real issue is that the binding wasn't able to connect to the table itself.

### Expected behavior
An error message that says something to the effect of "Wasn't able to find table x"

### Actual behavior
System.Private.CoreLib: Exception while executing function: TimerTriggerProducts. Microsoft.Azure.WebJobs.Host: Error while handling parameter products after function returned:. SqlBinding: Did not retrieve any primary keys for 'Products' in schema 'SCHEMA_NAME().' Cannot generate upsert command without them.

### Repo Steps
Create a table called [dbo].[Product] in the database and run the sample (instead of [dbo].[Products])

**Comment by Charles-Gagnon** [comment]
Closing trigger binding related issues until we revisit support for that

**Comment by Charles-Gagnon** [comment]
Look into creating the table if it doesn't exist

**Comment by chlafreniere** [comment]
> Look into creating the table if it doesn't exist

I've thought about this a bit more, and I certainly think that this part of it is lower pri, but if we did do this, I'm concerned that it may be a slippery slope/feature creep (e.g. could this further be expanded where a db needs to be created as well?)

My hypothesis from my super limited experience is that the vast majority of the time, users will hit this when they've misspelled the table name and/or schema. In this case, they wouldn't want the table created to begin with.

@dzsquared happy to hear your thoughts as well.
