### ISSUE TITLE
Add support for dynamic CommandText

### ISSUE THREAD

**Issue by SWarnberg** [Azure/azure-functions-sql-extension#341]
Hi,

It would be great to have the option of dynamically setting the `CommandText` property to use for output bindings. The use case is that you want to be able to use different tables based on what file that comes in a Blob input binding. Instead of creating one function per model/table, you can have one generic function for all models.

Staffan

**Comment by Charles-Gagnon** [comment]
You should be able to accomplish this with dynamic bindings - here's a simple example using an HttpTrigger that passes in the table name as a query parameter. 

```csharp
        [FunctionName("DynamicOutputBinding")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get")] HttpRequest req,
            IBinder binder
        )
        {
            var products = await binder.BindAsync<IAsyncCollector<Product>>(
                new SqlAttribute(req.Query["TableName"])
                {
                    ConnectionStringSetting = "SqlConnectionString"
                });
            var product = new Product() { ProductID = 1, Name = "Test Product", Cost = 100 };
            await products.AddAsync(product);
            return new CreatedResult($"/api/DynamicOutputBinding", product);
        }
```
