### ISSUE TITLE
SQL datetime, date, smalldatetime types not being handled correctly by output binding

### ISSUE THREAD

**Issue by glennamanns** [Azure/azure-functions-sql-extension#36]
Datetime2 is ok, but `datetime` appears to not be handled correctly by the T-SQL dynamically generated based on SQL column types. 

Example error:

`Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: GetProducts
---> System.InvalidOperationException: Error while handling parameter output after function returned:
---> Microsoft.Data.SqlClient.SqlException (0x80131904): Column, parameter, or variable #8: Cannot specify a column width on data type datetime.
Parameter or variable 'datetime' has an invalid data type.`

Example constraint:

`ALTER TABLE [SalesLT].[Address] ADD  CONSTRAINT [DF_Address_ModifiedDate]  DEFAULT (getdate()) FOR [ModifiedDate]`

@chlafreniere edit: same issue occurs with `date`, `smalldatetime` types as well.

**Comment by chlafreniere** [comment]
The issue lives in https://github.com/Azure/azure-functions-sql-extension/blob/main/src/SqlBinding/SqlAsyncCollector.cs#L268 but we need to understand why calling `datetime(3)` isn't working while `datetime2(3)` is happy as a clam. Need to read some docs for the right fix.
