### ISSUE TITLE
Review logging level for all log messages

### ISSUE THREAD

**Issue by Charles-Gagnon** [Azure/azure-functions-sql-extension#365]
Do a pass over all logging messages and make sure that they're at an appropriate level. 

Warning/Critical - Runtime errors, shown by default
Info - Things useful for the user to see with verbose logging enabled
Debug - Very detailed logging used for debugging issue (requires specifying debug log level in host.json)

**Comment by MaddyDev** [comment]
I've gone through the list of log messages that we currently have and are appropriately set. Closing this issue as we have #810 to go through adding diagnostic logging.
