### ISSUE TITLE
auto-generated identity column not getting auto-generated

### ISSUE THREAD

**Issue by engenb** [Azure/azure-functions-sql-extension#383]
I'm working with:
Microsoft.Azure.WebJobs.Extensions.Sql 0.1.457-preview

I have a table such as:
```sql
CREATE TABLE [dbo].[ReportJobs](
	[Id] [uniqueidentifier] NOT NULL,
	...

ALTER TABLE [dbo].[ReportJobs] ADD  DEFAULT (newsequentialid()) FOR [Id]
```

I have a C# poco:
```csharp
public class ReportJob
{
    public Guid Id { get; set; }
    ...
}
```
and a function with a sql output binding:
```csharp
[Sql($"dbo.{nameof(ReportJob)}s", ConnectionStringSetting = $"{nameof(ReportFactoryOptions.ConnectionStrings)}:{ReportFactoryOptions.ConnectionStrings.Database}")]
IAsyncCollector<ReportJob> reportJobs,
```

I've reviewed #189 and the updates to README.md and I believe I'd fall under scenario 2 of the [Primary Keys and Identity Columns](https://github.com/Azure/azure-functions-sql-extension/blob/main/README.md#primary-keys-and-identity-columns) "If the identity column is included" section:
_"If the identity column is included (even if it's an optional nullable value) then a merge is performed similar to what happens when no identity column is present. This merge will either insert a new row or update an existing row based on the existence of a row that matches the primary keys (including the identity column). See [AddProductWithIdentityColumnIncluded](https://github.com/Azure/azure-functions-sql-extension/blob/main/samples/samples-csharp/OutputBindingSamples/AddProductWithIdentityColumnIncluded.cs) for an example."_

^ the code comments in that linked sample indicate:
_"...the identity column is included in the output object. In this case the identity column is used to match the rows and all non-identity columns are updated if a match is found. Otherwise a new row is inserted (with the identity column being ignored since that will be generated by the engine)."_

The way I interpret those statements is, if I leave my Id as `default` (empty Guid) it won't match any existing rows and the identity column should be ignored and generated by the db.  However, that doesn't seem to be the case.  I've run sql profiler, and I can see that the generated script is not omitting Id, but is instead supplying the Id value with the insert.

```sql
EXEC sp_executesql 
    N'WITH cte AS ( SELECT * FROM OPENJSON(@rowData) WITH ([id] uniqueidentifier,[reporttype] nvarchar(max),[status] nvarchar(max),[glstart] datetime,[glend] datetime,[leasecount] int,[reporturi] nvarchar(max),[validated] datetimeoffset(7),[queued] datetimeoffset(7),[processing] datetimeoffset(7),[completed] datetimeoffset(7),[exception] datetimeoffset(7),[checksum] datetimeoffset(7),[dismissed] datetimeoffset(7)) ) 
                    MERGE INTO [dbo].[ReportJobs] WITH (HOLDLOCK)
                        AS ExistingData
                    USING cte
                        AS NewData
                    ON
                        ExistingData.[id] = NewData.[id]
                    WHEN MATCHED THEN
                        UPDATE SET  ExistingData.[Id] = NewData.[Id], ExistingData.[ReportType] = NewData.[ReportType], ExistingData.[GlStart] = NewData.[GlStart], ExistingData.[GlEnd] = NewData.[GlEnd], ExistingData.[LeaseCount] = NewData.[LeaseCount], ExistingData.[Status] = NewData.[Status], ExistingData.[ReportUri] = NewData.[ReportUri], ExistingData.[Validated] = NewData.[Validated], ExistingData.[Queued] = NewData.[Queued], ExistingData.[Processing] = NewData.[Processing], ExistingData.[Completed] = NewData.[Completed], ExistingData.[Exception] = NewData.[Exception], ExistingData.[Checksum] = NewData.[Checksum], ExistingData.[Dismissed] = NewData.[Dismissed]
                    WHEN NOT MATCHED THEN
                        INSERT ([Id],[ReportType],[GlStart],[GlEnd],[LeaseCount],[Status],[ReportUri],[Validated],[Queued],[Processing],[Completed],[Exception],[Checksum],[Dismissed]) VALUES ([Id],[ReportType],[GlStart],[GlEnd],[LeaseCount],[Status],[ReportUri],[Validated],[Queued],[Processing],[Completed],[Exception],[Checksum],[Dismissed]);'
    ,N'@rowData nvarchar(max) '
    ,@rowData = N'[{"id":"00000000-0000-0000-0000-000000000000","reporttype":0,"status":2,"glstart":"2022-10-01T00:00:00.000","glend":"2022-10-31T11:59:59.999","leasecount":0,"reporturi":null,"validated":"2022-10-05T22:19:44.689","queued":"2022-10-05T22:19:44.756","processing":null,"completed":null,"exception":null,"checksum":null,"dismissed":null}]'
```

A follow-up question: if this was working, what is the intended approach to retrieve the value of the generated id so that I may return it from my function?  Would it be possible to include `OUTPUT INSERTED.*` to retrieve any database-generated values and then update the C# poco with these values?

Thanks for taking a look!

**Comment by Charles-Gagnon** [comment]
So Identity columns in this case are a special type of column - https://learn.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql-identity-property?view=sql-server-ver16

You would declare this like so in your CREATE TABLE script

```sql
CREATE TABLE [dbo].[ReportJobs](
	[Id] [int] PRIMARY KEY NOT NULL IDENTITY(1,1),
	...
```

Note that identity columns can only be integers - you can't have a GUID identity column for example. 

In your case it seems like this isn't even a primary column - you just have a default column that is incorrectly being assigned a default value (`00000000-0000-0000-0000-000000000000` in the case of GUIDs). 

In which case it seems like we should look into whether we can add logic to skip default columns when creating the merge statement if no value is provided, since that'll be generated by the database.

**Comment by engenb** [comment]
Sorry for missing that detail in my description.  `[Id]` is my table's PK, I just missed grabbing that bit of sql

```sql
CREATE TABLE [dbo].[ReportJobs](
	[Id] [uniqueidentifier] NOT NULL,
	...
    CONSTRAINT [PK_dbo.ReportJobs] PRIMARY KEY CLUSTERED 
    (
	[Id] ASC
    )
)
```
but your explanation is helpful.  It seems that int/identity PKs are supported, but Guid/uniqueidentifier PKs are not

**Comment by Charles-Gagnon** [comment]
Ah, gotcha. Either way though we don't currently do anything with default columns which is definitely an issue. 

We need to be careful about the nullability of the column for default columns - here's how I think it should work : 

1. If a column has a default value (whether the column is nullable or not) then it is optional for having in the POCO. It'll just pick up the default value when inserted in if the object doesn't have it
2. If a column IS nullable and the object has that field defined then we'll use that value - even if it's NULL

@lucyzhang929 Does that make sense?

**Comment by lucyzhang929** [comment]
Yep that makes sense!

**Comment by engenb** [comment]
Any thoughts about utilizing `OUTPUT INSERTED.*` to retrieve any db-generated/updated values to update the entity?  I think it must be a pretty common use case to want to output the generated id from the function.  Beyond just ids, I also make use of concurrency tokens which are managed by the db as well.

**Comment by Charles-Gagnon** [comment]
I'll add that to https://github.com/Azure/azure-functions-sql-extension/issues/267 since they're essentially the same ask

**Comment by Charles-Gagnon** [comment]
I left a comment in the linked issue though since I'm not really sure how this would even look. How would the function get these values to be used? (if you have ideas let's use that other issue for discussing that particular feature further)

**Comment by lucyzhang929** [comment]
> Ah, gotcha. Either way though we don't currently do anything with default columns which is definitely an issue.
> 
> We need to be careful about the nullability of the column for default columns - here's how I think it should work :
> 
> 1. If a column has a default value (whether the column is nullable or not) then it is optional for having in the POCO. It'll just pick up the default value when inserted in if the object doesn't have it
> 2. If a column IS nullable and the object has that field defined then we'll use that value - even if it's NULL
> 
> @lucyzhang929 Does that make sense?

@Charles-Gagnon Created a PR to address 1. For 2, that is already the current behavior (if the nullable column is included in the POCO, then null will be used).

**Comment by lucyzhang929** [comment]
@engenb The latest release (https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Sql/0.1.483-preview) contains the fix for this issue. Please let us know if you are still seeing issues after the update.
