### ISSUE TITLE
Trigger support for isolated model (out of proc)

### ISSUE THREAD

**Issue by MaddyDev** [Azure/azure-functions-sql-extension#384]
As part of out of proc support, we need to add trigger binding attribute metadata to the sql worker extension. Since right now we don't have the trigger implementation in main, add this as soon as it gets merged.

**Comment by Charles-Gagnon** [comment]
Do you need that to actually be in main? You can just use the triggerbindings branch and add it there after you're done with the input/output bindings.

**Comment by MaddyDev** [comment]
Yep I could do that as well once I get my changes in main

**Comment by MaddyDev** [comment]
#750 adds this.
