### ISSUE TITLE
Serialization issue with Date in JavaScript Output Bindings

### ISSUE THREAD

**Issue by lucyzhang929** [Azure/azure-functions-sql-extension#385]
Original issue (IAsyncCollector section): https://github.com/Azure/azure-functions-sql-extension/issues/316

We added ISO DateTime Format to the serialization settings but as noted [here](https://github.com/Azure/azure-functions-sql-extension/blob/a916d353b0f04dad8f66cbcc1e8944bf512fc8c2/src/SqlAsyncCollector.cs#L339), the serialization settings are ignored in JavaScript.

If the Date passed in is not ISO format, we get the following error
`Conversion failed when converting date and/or time from character string.`

**Comment by MaddyDev** [comment]
@lucyzhang929 Is this still a valid issue in JavaScript since we made some changes overall to default time to ISO format and removed the code mentioned [here](https://github.com/Azure/azure-functions-sql-extension/blob/a916d353b0f04dad8f66cbcc1e8944bf512fc8c2/src/SqlAsyncCollector.cs#L339)

**Comment by lucyzhang929** [comment]
In CSharp, we always convert the date to ISO format but this doesn't happen for non-csharp languages. So if a date is passed in a different format, the database will throw an error.

I'll close this issue for now since we documented the expected format in the readme and all our samples use ISO format for datetime.
