### ISSUE TITLE
Trying the trigger and getting an error

### ISSUE THREAD

**Issue by dkboon01** [Azure/azure-functions-sql-extension#399]
I'm getting this error  Failed to compose trigger parameter value for table: 'dispatch due to exception: Newtonsoft.Json.JsonReaderException. Exception message: Could not convert string to integer: AAAAABGrxfo=. Path 'ut', line 1, position 355.         Dispatch is the name of my table 

I know the change tracking table is working because I'm able to see the changes using this query
*******************************************************************************************************************************
declare @last_synchronization_version bigint;  /**sync version look at last query**/

DECLARE @PhotoColumnId int = COLUMNPROPERTY(OBJECT_ID('dbo.dispatch'),'status', 'ColumnId');   /*looking dispatch status change*/
select @PhotoColumnId, object_id('dbo.dispatch'), @last_synchronization_version
SELECT
    CT.Id, P.Billto, CT.*,P.status, -- Always obtain values.
    CASE
           WHEN CHANGE_TRACKING_IS_COLUMN_IN_MASK(
                     @PhotoColumnId, CT.SYS_CHANGE_COLUMNS) = 1
            THEN status 
            ELSE NULL
      END AS CT_ThumbNailPhoto,
      CHANGE_TRACKING_IS_COLUMN_IN_MASK(
                     @PhotoColumnId, CT.SYS_CHANGE_COLUMNS) AS
                                   CT_ThumbNailPhoto_Changed,
     CT.SYS_CHANGE_OPERATION, CT.SYS_CHANGE_COLUMNS,
     CT.SYS_CHANGE_CONTEXT
FROM
    dispatch AS P
INNER JOIN
     CHANGETABLE(CHANGES dispatch, @last_synchronization_version) AS CT
ON
     P.Id = CT.Id AND
     CT.SYS_CHANGE_OPERATION = 'U';
********************************************************************************************************

**Comment by dkboon01** [comment]
We have an api that hits the database table using C#. I'm looking for the exact piece of code that changes the "status"
The status being changed is what I'm looking for. In my query above I was just making sure that the change tracking is turned on for the table and the columns.   (it is one of the queries in the microsoft docs on change tracking )  I have attached my table schema dispatch and I don't see any binaries fields.  )  I have no idea where it is getting binary types.
[dispatch.zip](https://github.com/Azure/azure-functions-sql-extension/files/9832236/dispatch.zip)

**Comment by JatinSanghvi** [comment]
Hi @dkboon01, I am unable to understand how the function is setup on your end. It would be far easier for us to help you of you can share a minimal function and a minimal table schema that would let us reproduce the same error that you are getting.

**Comment by dkboon01** [comment]
I'm trying to create a new project to send to you.    In the new project, I have added the nuget package through the nuget package manager but it keeps complaining that the attributes like SQLChange , SQLTrigger are not found to compile.  Is there something in vs 2022 setup that would prevent it from using the preview package? When I try to build the project the same error messages occur. 
![Screenshot 2022-10-26 084521](https://user-images.githubusercontent.com/11353230/198029943-ae594fcc-8aab-41a9-9b87-fdaac7c52205.png)
![Screenshot 2022-10-26 085021](https://user-images.githubusercontent.com/11353230/198030427-6fc1fdfb-8b59-4527-9e16-7875bda8f492.png)

**Comment by Charles-Gagnon** [comment]
SqlTrigger functionality is currently not in the public package yet - we'll be adding it to that soon so keep an eye out for that!

**Comment by dkboon01** [comment]
Thank you Charles-Gagnon that worked for me.  One last question, we have a home grown ORM system that usually brings in the table class definition.  Does the SQL trigger have to use entity framework?   I have always used EF or Dapper so what I did to get rid of the binary error was to create a class definition of dispatch using entity framework core and now it works. My next step is to leave the class dispatch the way it is and take away the EF packages that I had to add to generate the dispatch class using dotnet ef from commandline.  But before I break it again I was wondering if EF is a requirement.

**Comment by Charles-Gagnon** [comment]
There is no EF requirement - you can use whatever you want to generate the class definitions. 

Are you still seeing the original error you mentioned or has that gone away?

**Comment by dkboon01** [comment]
When I generate the class for dispatch table using EF everything works.  However, I tried to use a class generated by our custom ORM and it does not work.  I will have to be work on this in more detail. For now, i will just use the EF class generation.  Should I be able to have two output bindings on the SQLTrigger?  Like this 
 [SqlTrigger("Dispatch",ConnectionStringSetting ="SqlTestConnectionString")]
             IReadOnlyList<SqlChange<Dispatch2>> changes,
             [SignalR(HubName = "ABCHub")]  IAsyncCollector<SignalRMessage> signalRMessages,
              ILogger logger

**Comment by dkboon01** [comment]
So I figured out the issue with the getting the json error above.   The issue is this:   We have a column in the table that is defined as timestamp the name of the column is ut.   When I do a dotnet scaffold using EF, the class it generates for this table makes this column a byte[] with ut as the column.  However, our ORM custom system is not adding this column at all on the generated class.  
The only question I have outstanding is about adding a SignalR output binding to the SQLTrigger.  In the above comment, should this work? It would be nice that once I encounter the change of status that i could notify the UI via SignalR of the change.

**Comment by Charles-Gagnon** [comment]
Yup, that should work fine! It's a very common scenario to have a function with multiple bindings like that. In fact nearly all of our samples have an HttpTrigger with a SQL Input or Output binding : https://github.com/Azure/azure-functions-sql-extension/blob/main/samples/samples-csharp/OutputBindingSamples/AddProduct.cs

**Comment by Charles-Gagnon** [comment]
@dkboon01 Is there any issues you're still having or can we close this?

**Comment by dkboon01** [comment]
Yes, please close. Is there any update on when this will be released out of preview? I would like to use this in a production environment soon.

**Comment by Charles-Gagnon** [comment]
The trigger binding is still is private preview right now.

We'll be releasing it into public preview here this month.

GA date for the extension is TBD, but will be next year some time.
