### ISSUE TITLE
[Language Support] NodeJS

### ISSUE THREAD

**Issue by mpth** [Azure/azure-functions-sql-extension#40]
Hey there,

can this extensoin be used in functions written in NodeJS? If so could you provide a sample of how the output and input bindings can be used?

Thanks ❤️

**Comment by mcavaciocchi** [comment]
it would be nice

**Comment by ericwilhite** [comment]
Would SQL input/output bindings for NodeJS handle connection pooling issues with serverless? I've got a read/write heavy API I'd love to abstract into serverless functions but worry the constant connect/disconnect will overload the database.

**Comment by Charles-Gagnon** [comment]
@dzsquared Does this still need to be open?

**Comment by dzsquared** [comment]
https://docs.microsoft.com/azure/azure-functions/functions-bindings-azure-sql?tabs=in-process%2Cextensionv3&pivots=programming-language-javascript
