### ISSUE TITLE
problem with decode of sqlrows to ascii

### ISSUE THREAD

**Issue by FortydaysofTXRain** [Azure/azure-functions-sql-extension#402]
I have been testing using the input SQL bindings in a python (linux) Azure Function to read row lists from a database hosted on  database.windows.net but I am having trouble with the decoded rows showing mangled unicode characters. 

I follow the tutorial on https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-azure-sql-input?source=recommendations&tabs=in-process&pivots=programming-language-python

```{python}
# azure function init.py
import azure.functions as func
import json

def main(req: func.HttpRequest, todoItems: func.SqlRowList) -> func.HttpResponse:
    rows = list(map(lambda r: json.loads(r.to_json()), todoItems))

    return func.HttpResponse(
        json.dumps(rows),
        status_code=200,
        mimetype="application/json"
    )
```
and use a command text of
`SELECT DISTINCT colA FROM my.table.view` 

I expect to get back a json like
`[{"colA":"my value 1"},{"colA":"myvalue 2"}]` (which is what I would get in MSSM or using the pyodbc python module to make the query)
Instead I get b`[{"colA":"my\\u00a0value\\u00a01"},{"colA":"myvalue\\u00a02"}]` as the byte response to the http trigger for the function or if I use logging to print the rows from within the function.

I am look for a way to ensure that the dictionaries returned from my SQL queries don't have bad characters.

**Comment by lucyzhang929** [comment]
Closing this issue since I am unable to reproduce and no response. @FortydaysofTXRain, if you are still facing this issue, please feel free to reopen the issue.
