### ISSUE TITLE
[Runtime Support] out of proc

### ISSUE THREAD

**Issue by mpth** [Azure/azure-functions-sql-extension#41]
Just tried to use this extension with the new isolated process functions runtime and it seems it is not supported yet

`...is a WebJobs attribute and not supported in the .NET Worker (Isolated Process)` 

Or am I doing something wrong?

**Comment by fabiocav** [comment]
That's correct. I was going to create a tracking item in the worker repo but just noticed this is not yet in NuGet. I'm inclined to say we should wait until we have a publicly published preview before creating the extension there. 

Thoughts?

**Comment by anthonychu** [comment]
I think we should start adopting the model of putting the "buddy" packages in the same repo as the extension. So I think we should add it here and publish it to MyGet.

**Comment by dzsquared** [comment]
Related to #88

**Comment by KenBrannigan** [comment]
Any update on when the isolated model will be supported by this extension?

**Comment by MaddyDev** [comment]
Isolated model is now available! Please refer [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-azure-sql-input?tabs=isolated-process&pivots=programming-language-csharp#tabpanel_1_isolated-process)

**Comment by KenBrannigan** [comment]
I apologize I was not specific enough. When will the SqlTrigger be available in the isolated model?

**Comment by MaddyDev** [comment]
> I apologize I was not specific enough. When will the SqlTrigger be available in the isolated model?

We have just released the isolated input output bindings support, we've the below to track the trigger isolated support which we're planning on adding real soon: 
https://github.com/Azure/azure-functions-sql-extension/issues/384
