### ISSUE TITLE
Managed identity authentication

### ISSUE THREAD

**Issue by u000fsr** [Azure/azure-functions-sql-extension#42]
Using your examples I was able to setup a function app sql trigger using an azure sql db instance with change tracking enabled. Running it locally it seems to work well, however I want to deploy the code to a function app in azure that would connect to the database using its managed identity. I don't see how this is possible as the sdk is only taking a connection string. Enabling managed identity I believe requires the use of Microsoft.Azure.Services.AppAuthentication to call the local token endpoint for a token which would be passed to the AccessToken property on the sql connection, unless I'm missing something.

**Comment by dzsquared** [comment]
The managed identity handling is part of the connection string, which in turn is used by SqlClient (behind the scenes) to broker the authentication.

https://docs.microsoft.com/en-us/azure/azure-functions/functions-identity-access-azure-sql-with-managed-identity

Example connection string using the Function's system-assigned identity:

`Server=demo.database.windows.net; Authentication=Active Directory Managed Identity; Database=testdb`
