### ISSUE TITLE
MongoDB Support

### ISSUE THREAD

**Issue by WingZer0123** [Azure/azure-functions-sql-extension#447]
I came across this project and plan on going through the tutorials for the SQL Server portation using .NET Core 3.1. I have a side project that I work on.

Is there any support for executing stored JavaScript in MongoDB?

**Comment by dzsquared** [comment]
I suspect what you're looking for is well outside of the scope of this integration, if you're looking to pull JavaScript from MongoDB documents and then execute it server-side.

Overall, you might find the CosmosDB input/output bindings useful (https://learn.microsoft.com/azure/azure-functions/functions-bindings-cosmosdb-v2) as well as the more general Azure Functions repository (https://github.com/Azure/Azure-Functions/).
