### ISSUE TITLE
Automatically copy locally built DLLs 

### ISSUE THREAD

**Issue by VasuBhog** [Azure/azure-functions-sql-extension#459]
In order to test scripting languages (PowerShell, Javascript and etc) with the latest Dll builds, one must (**currently**) do the following:

1. Run dotnet build in the root of the repo
2. Copy the DLL in src/bin/Debug/netstandard2.0 to the extension bundle (samples you want to test - step 3).
3. Go to the directory of the extension bundle you want to change - for example azure-functions-sql-extension/samples/samples-powershelland usefunc GetExtensionBundlePath` to see where to copy the DLL found in step 2 into.
4. Copy the DLL from step 2 to the path found in step 3 and run Dotnet test at the root of the repo as it should use the latest builds then.

It would be better to make this an automated task - possibly as embedded as a startup task in the tests themselves.

**Comment by Charles-Gagnon** [comment]
@VasuBhog Please add the manual steps to https://github.com/Azure/azure-functions-sql-extension/blob/main/test/README.md
