### ISSUE TITLE
GetFunctionsCoreToolsPath fails to find Azure Function Core Tools on Mac

### ISSUE THREAD

**Issue by VasuBhog** [Azure/azure-functions-sql-extension#461]
On Mac: Azure Function Core tools is (most likely) installed via Brew. 

Therefore the GetFunctionCoreTools will fail on finding the core tools in node modules (shown below):

`System.IO.FileNotFoundException : Azure Function Core Tools not found at /usr/local/lib/node_modules/azure-functions-core-tools/bin/func`.

We should also check brew for Mac OS development so that it can properly find the function core tools path and not have to hardcode the path.

Workaround: 
- comment out `GetFunctionsCoreToolsPath` and set this [line](https://github.com/Azure/azure-functions-sql-extension/blob/main/test/Integration/IntegrationTestBase.cs#L191) to where the location of func is (use `where func` in the terminal to find the location).

**Comment by lucyzhang929** [comment]
Fixed here: https://github.com/Azure/azure-functions-sql-extension/pull/533
