### ISSUE TITLE
Add Integration tests for scaling support

### ISSUE THREAD

**Issue by Charles-Gagnon** [Azure/azure-functions-sql-extension#500]
Currently only have unit tests, we should be actually verifying it works as expected (at the very least ensure the queries can run)

**Comment by Charles-Gagnon** [comment]
@JatinSanghvi Do you have any ideas here? My current plan is just to have a test that runs the scaling queries so we can avoid breaks like happened recently - but that won't actually be verifying scaling itself works. But is that something we can even test with the function core tools? Or will we need to deploy a function to actually verify that full end-to-end scenario?

**Comment by JatinSanghvi** [comment]
The Functions core tools (along with WebJobs SDK) contains the logic to:
- Hosting the HTTP APIs that ScaleController can query to fetch scaling metrics.
- Forwarding the request for metrics to the respective extension.
- Caching the metrics (in storage account table if I am correct) so it can supply a list of metrics every time to the extension and it can know if the load is trending up or down.

So, there should be a way to test the above behaviors with just the core tools. We will need to get help from engineers in Azure Functions team to know if this is feasible without requiring a change in Functions runtime host, and if there is another extension already performing integration testing like this. I am not sure if this will be able to be a significant improvement over unit tests.

The ScaleController is the component responsible for actual scaling the Function App (with or without runtime driven scaling enabled). So, if we want to perform a complete end-to-end integration testing, we will need to have a Function App published, and for each test run, we will need to publish the code to this Function App and generate the load on an external SQL server to ensure that Function App is able to scale in and out. If we have a fixed Function App, we will need to make such test part of periodic (e.g., nightly) testing to ensure that the only one test is running at a time. If we make it part of CI test, then even Function App will need to be created every time, which can add to complexity and test completion time.

Note that the ScaleController does not have deterministic behavior (in my experience). It can sometimes take long intervals between polling for metrics, and sometimes there is a significant time delay after a scale-out is requested by the extension and it actually scales out the app, so we will possibly not be able to add precise assertion-statements (i.e., app scaled out to 4 instances after 2 minutes) in such tests.

**Comment by Charles-Gagnon** [comment]
That's great info, thanks. I'm planning on just keeping what we have for now since it should be fairly certain that the function runtime scaling logic is working correctly (and we have tests that our logic is working) and given the complexity of setting something like that up but I'll keep that in mind for when we're looking to increase automated coverage in the future.
