### ISSUE TITLE
Add more detailed information for encryption failures

### ISSUE THREAD

**Issue by Charles-Gagnon** [Azure/azure-functions-sql-extension#504]
With the update to SqlClient 5 customers may run into SqlClient errors because of the default encryption change. It would be good to catch that error and throw a more detailed information that includes a link to information about how to fix it - such as was done in https://github.com/microsoft/azuredatastudio/pull/21036. This can be done pretty early on since the initial function startup queries the database which will immediately fail - so as long as the first query executed has this check that'd be enough. 

This will help avoid confusion from customers hitting this and hopefully let them self-diagnose and fix the issue instead of filing a bug or opening a help ticket. 

https://learn.microsoft.com/en-us/troubleshoot/sql/connect/error-message-when-you-connect

**Comment by chlafreniere** [comment]
We've also done something similar in DacFx: https://techcommunity.microsoft.com/t5/azure-sql-blog/connection-security-improvements-in-sqlpackage-161/ba-p/3672758
