### ISSUE TITLE
Enable triggers without using SQL's change tracking functionality

### ISSUE THREAD

**Issue by JhanviChauhan** [Azure/azure-functions-sql-extension#51]
In certain use cases, users do not own the database that they are polling on and only have access to a connection string provided by the table owner. User does not have the ability to alter the table and enable sql change tracking in such cases.

Is it possible to use existing [RowVersion ](https://docs.microsoft.com/en-us/sql/t-sql/data-types/rowversion-transact-sql?view=sql-server-ver15)and (monotonically increasing) [Identity ](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql-identity-property?view=sql-server-ver15)columns in the table to poll for modified rows and newly-added rows respectively?

**Comment by Charles-Gagnon** [comment]
Closing trigger binding related issues until we revisit support for that
