### ISSUE TITLE
Improve documentation for how to run and debug tests locally

### ISSUE THREAD

**Issue by VasuBhog** [Azure/azure-functions-sql-extension#512]
VSCode Local Development.

There should either be information on what tests failed once `dotnet test` is completed, as it currently just output something like below example:
`Failed!  - Failed:     3, Passed:    60, Skipped:     0, Total:    63, Duration: 11 m 18 s - /Users/vasubhog/GitProjects/azure-functions-sql-extension/test/bin/Debug/net6/Microsoft.Azure.WebJobs.Extensions.Sql.Tests.dll (net6.0)`

This is not informative about what tests failed and you may not be able to scroll up if the terminal does not allow it since we run many tests.

Possible Solution:
Have the tests that failed to be saved to a list so that at the end they be outputted in order to quickly understand which tests fail and then focus on.

**Comment by Charles-Gagnon** [comment]
The test failure information is in the logs already - although when looking at pipeline failures you should typically be using the tests tab for this since it also directly attaches the stdout for the test that failed as well. Is there something else you think we need here?

**Comment by Charles-Gagnon** [comment]
And if you really just want to run from the command line then you can just use `dotnet test --logger:html` and that will output an HTML file with all the test failure details

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-test has all the details on that (and more options)

![image](https://user-images.githubusercontent.com/28519865/202235188-a8bb1217-1e91-4c66-a8c5-38a7801fb6d8.png)

**Comment by VasuBhog** [comment]
> It has a test explorer as well which should provide a similar experience for seeing test failures and their results. Running dotnet test directly is not something I would expect most people to be doing when working on tests locally.

I only use VS Code for local development. Are you talking about this test explorer extension? https://marketplace.visualstudio.com/items?itemName=formulahendry.dotnet-test-explorer. 

It would be great to include some of this information in the [Integration Test ReadMe](https://github.com/Azure/azure-functions-sql-extension/blob/main/test/README.md) specifically running tests since that is not stated.

**Comment by Charles-Gagnon** [comment]
Something like that - I've never tried using that myself since VS is just a much better experience IMO. Feel free to add any documentation you think is necessary.

**Comment by VasuBhog** [comment]
Updated test docs [here](https://github.com/Azure/azure-functions-sql-extension/tree/main/test#function-host) so that there are multiple ways to debug.
