### ISSUE TITLE
Foreign keys require specific output binding ordering

### ISSUE THREAD

**Issue by jnsvd** [Azure/azure-functions-sql-extension#542]
When 2 records are created through an output binding where a foreign key constraint exists between their tables, an exception is thrown if the order of the `bindings` does not respect the order in which the records should be created.

**Test setup**

Using the following tables:

```
CREATE TABLE TransactionData
(
    TransactionDataID uniqueidentifier NOT NULL,
    Data              nvarchar(max)    NOT NULL,
    CONSTRAINT PK_TransactionData PRIMARY KEY (TransactionDataID)
);

CREATE TABLE Transaction
(
    TransactionID     uniqueidentifier NOT NULL,
    Timestamp         datetime         NOT NULL,
    TransactionDataID uniqueidentifier NOT NULL,
    CONSTRAINT PK_Transaction PRIMARY KEY (TransactionID),
    CONSTRAINT FK_Transaction_TransactionData FOREIGN KEY (TransactionDataID) REFERENCES TransactionData (TransactionDataID)
)
```

with the following in `function.json`:

```
{
  "bindings": [
    {
      "name": "transaction",
      "type": "sql",
      "direction": "out",
      "commandText": "dbo.[Transaction]",
      "connectionStringSetting": "SqlConnectionString"
    },
    {
      "name": "transactionData",
      "type": "sql",
      "direction": "out",
      "commandText": "dbo.[TransactionData]",
      "connectionStringSetting": "SqlConnectionString"
    }
  ]
}
```

and the following in `index.js`:

```
const crypto = require('crypto');

module.exports = async function (context) {
  const TransactionDataID = crypto.randomUUID();
  context.bindings.transactionData = {
    TransactionDataID,
    Data: 'Some transaction data',
  };
  context.bindings.transaction = {
    TransactionID: crypto.randomUUID(),
    Timestamp: new Date().toISOString().slice(0, 19).replace('T', ' '),
    TransactionDataID,
  }
}
```

**Observations**

The following exception is thrown:

```
[2022-11-30T14:47:18.776Z] Executed 'Functions.SendTransaction' (Failed, Id=7a9cfde4-0bac-4f1b-8714-1769af1ca772, Duration=4345ms)
[2022-11-30T14:47:18.776Z] System.Private.CoreLib: Exception while executing function: Functions.SendTransaction. Microsoft.Azure.WebJobs.Host: Error while handling parameter _binder after function returned:. Core Microsoft SqlClient Data Provider: The MERGE statement conflicted with the FOREIGN KEY constraint "FK_Transaction_TransactionData". The conflict occurred in database "master", table "dbo.TransactionData", column 'TransactionDataID'.
[2022-11-30T14:47:18.776Z] The statement has been terminated.
```

The function runs correctly if the order of the bindings is changed:

```
{
  "bindings": [
    {
      "name": "transactionData",
      "type": "sql",
      "direction": "out",
      "commandText": "dbo.[TransactionData]",
      "connectionStringSetting": "SqlConnectionString"
    },
    {
      "name": "transaction",
      "type": "sql",
      "direction": "out",
      "commandText": "dbo.[Transaction]",
      "connectionStringSetting": "SqlConnectionString"
    }
  ]
}
```

**Potential solution**

Allow to explicitly configure dependencies between output records, or improve documentation to more clearly explain this.

**Comment by Charles-Gagnon** [comment]
Ah found the docs - and yeah dynamic (imperative) binding is only for .NET languages : https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-expressions-patterns#binding-at-runtime

**Comment by jnsvd** [comment]
Thank you for clarifying @Charles-Gagnon. 
I have the option to drop the foreign key constraint. This is not ideal, but a much better solution than using additional functions with triggers or directly using the `mssql` client library to perform the inserts.

> I don't think there's anything we can do here either - the binding code knows nothing about the rest of the bindings in the function and so there's no way to look up the tables from the other binding.
If the bindings were indeed deterministic and handled in the same transaction, there would be no problem. There is probably room for improvement there. I'm also facing issues where messages are put on a Service Bus through another binding, where the function processing the message does not yet 'see' a database record that's created through another binding. Ideally every reader would get a consistent view of the data created through the output bindings.

**Comment by Charles-Gagnon** [comment]
Yeah, I agree it would be nice. But given the comments on the issue I linked that seems unlikely to happen anytime soon unfortunately.

I'll add something to our docs about this since it seems like good information to know about for people trying to write these.

When you say "If the bindings were indeed deterministic and handled in the same transaction" - do you mean the same T-SQL transaction? Or just in general where all Function bindings were executed together in the same "batch" (or something along those lines)?

**Comment by Charles-Gagnon** [comment]
Another way to solve this would be if you were able to use a .NET function then you could use an IAsyncCollector which would let you control when the data was upserted. There isn't a way to do that for non-.NET functions though unfortunately.
