### ISSUE TITLE
Enable TimerTrigger test for OOP

### ISSUE THREAD

**Issue by MaddyDev** [Azure/azure-functions-sql-extension#550]
Currently the TimerTrigger sample works as expected but the test keeps failing with the below error:

No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

**Comment by Charles-Gagnon** [comment]
Are you looking into this builder.AddTimers() call? Seems like a good place to start
