### ISSUE TITLE
Cancellation Tokens Not Leveraged in Repo

### ISSUE THREAD

**Issue by chlafreniere** [Azure/azure-functions-sql-extension#57]
I haven't seen any cases where cancellation tokens are actually being used. Is this typical for AF extensions, or is there more work to do to make this production-ready?

**Comment by Charles-Gagnon** [comment]
Investigate how cancellation tokens are used in other AF's

**Comment by chlafreniere** [comment]
@Charles-Gagnon can you help with some investigation here? If there's work to do pre-preview, we can assign work to whoever has capacity, but just understanding if there's work to do would be super helpful

**Comment by chlafreniere** [comment]
This isn't strictly true anymore (after https://github.com/Azure/azure-functions-sql-extension/commit/08d8f62afbe89c169c68905c2f39f963630d369e) but still good to investigate

**Comment by lucyzhang929** [comment]
We do not need to use the cancellation token in our upsert method since we are wrapping the upsert in a SqlTransaction. This will prevent any partial data from being left in the table.
