### ISSUE TITLE
SQLTrigger - Error => Reconnect to SQL Server 

### ISSUE THREAD

**Issue by Jetro223** [Azure/azure-functions-sql-extension#593]
I am using a SqlTrigger to get changes from a Azure SQL Database table.

```c#
public void Run(
            [SqlTrigger("[raw].[transferMessage]", ConnectionStringSetting = "SqlConnectionStringRaw")]
            IReadOnlyList<SqlChange<TransferMessage>> changes, ILogger log)
{
}
```

When the connection to the Azure SQL DB is lost (scaling of the elastic pool/ manual kill of the connection) the function logs the following every second:

`Failed to check for changes in table 'raw.transferMessage' due to exception: System.InvalidOperationException. Exception message: Invalid operation. The connection is closed.`

It's necessary to restart the function app to resume operation. 

Is there anything like auto-reconnect which I'm missing from the docs or what can I do?

Edit: 
Adding ConnectRetryCount=50;ConnectRetryInterval=10 to the connection string does not work when scaling the database

**Comment by Charles-Gagnon** [comment]
Unfortunately no, currently you will need to restart the app.

This is definitely something we'll want to address though. The most straightforward would be just to check if the connection is closed before each iteration of the loop and attempt to reopen it if isn't. That should cover any scenario where the connection is closed unexpectedly.
