### ISSUE TITLE
Document types of auth supported

### ISSUE THREAD

**Issue by Charles-Gagnon** [Azure/azure-functions-sql-extension#607]
Provide links to instructions as necessary

Managed Identity - https://learn.microsoft.com/azure/azure-functions/functions-identity-access-azure-sql-with-managed-identity

**Comment by dzsquared** [comment]
expand this section on auth in the public docs: https://msdata.visualstudio.com/SQLToolsAndLibraries/_wiki/wikis/SQLToolsAndLibraries.wiki/45072/External-File-Format-Options-for-Delimited-Text-Support-in-DacFx
