### ISSUE TITLE
Document retry handling for bindings

### ISSUE THREAD

**Issue by Charles-Gagnon** [Azure/azure-functions-sql-extension#609]
When retries happen and how the user can configure them (if possible). This includes: 

- Function level retries (e.g. an exception is thrown when executing user function in trigger binding or an error is thrown when trying to insert data from an output binding)
- Internal retries (e.g. [trying to recover a broken connection in trigger binding](https://github.com/Azure/azure-functions-sql-extension/pull/599)) 

- [x] Input binding retry docs
- [x] Output binding retry docs
- [x] Trigger binding retry docs
- [x] Update [public docs](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=fixed-delay%2Cin-process&pivots=programming-language-csharp#retries)

**Comment by dzsquared** [comment]
to include https://github.com/Azure/azure-functions-sql-extension/blob/main/docs/BindingsOverview.md#retry-support-for-trigger-bindings in the public docs

**Comment by Charles-Gagnon** [comment]
Need to investigate setting up function level retry

Sample PRs : 

https://github.com/Azure/azure-functions-kafka-extension/pull/363
https://github.com/Azure/azure-functions-kafka-extension/pull/375

**Comment by dzsquared** [comment]
Input/output retry handling now in usage section on public docs (https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-azure-sql-input?tabs=in-process&pivots=programming-language-csharp#usage) - @Charles-Gagnon anything else on this issue for which we want to keep it open?

**Comment by Charles-Gagnon** [comment]
Looks great, thank you Drew!
