### ISSUE TITLE
Improper identifier quoting

### ISSUE THREAD

**Issue by Charles-Gagnon** [Azure/azure-functions-sql-extension#63]
There are places in the code where identifiers are being bracket-quoted but done so incorrectly. e.g. 

https://github.com/Azure/azure-functions-sql-extension/blob/main/src/SqlBinding/SqlBindingUtilities.cs#L184
https://github.com/Azure/azure-functions-sql-extension/blob/main/src/SqlBinding/SqlBindingUtilities.cs#L195

When doing this we need to also escape the closing brackets, otherwise any names with a closing bracket in it will create an invalid identifier (e.g. `my]table` -> `[my]table]`, it should be `[my]]table]`)

**Comment by Charles-Gagnon** [comment]
Something to consider if we find other common functionality like this is whether we can use a shared library for this stuff - SMO does a lot of similar logic but that isn't really exposed in a way that could easily be used without pulling in all of SMO.

**Comment by lucyzhang929** [comment]
The method that was bracket-quoting identifiers was removed as part of the trigger bindings code so I'll close this issue for now. If needed in the future, we can add a method similar to QuoteIdentifier
https://github.com/Azure/azure-functions-sql-extension/blob/88613533b24a3efed484a60b01982060f75ce37f/src/SqlBinding/SqlBindingUtilities.cs#L171-L174
