### ISSUE TITLE
Document SQL Client configuration

### ISSUE THREAD

**Issue by Charles-Gagnon** [Azure/azure-functions-sql-extension#638]
Give a brief blurb in our docs about how SQL Client is used for all connections/queries and provide a link to the various configuration the user can control through the connection string (for example, things like pooling and connection timeouts). This will help customers understand what configurations they have control over and how to set them. 

This does NOT include anything we specifically change/handle in our extension - for example the reconnect retry logic.

**Comment by dzsquared** [comment]
Now on the docs: https://aka.ms/sqlbindings
![image](https://user-images.githubusercontent.com/12227241/231794794-95025215-f50d-4aa7-9834-ab5540a30fad.png)
