### ISSUE TITLE
Add unit tests for Out Of Proc worker

### ISSUE THREAD

**Issue by Charles-Gagnon** [Azure/azure-functions-sql-extension#651]
We currently have unit tests for the main extension code itself, but not any for the worker. 

It looks like we won't be able to directly add them to the existing unit test project so likely a separate project will have to be made for adding those - but the tests themselves should be mostly copies of what we already have with some minor adjustments made for the differing attributes/libraries.

**Comment by MaddyDev** [comment]
#661 adds worker unit tests, Closing this.
