### ISSUE TITLE
Missing System.Configuration.ConfigurationManager error on startup with bundle version 4.4.0

### ISSUE THREAD

**Issue by maersk96** [Azure/azure-functions-sql-extension#664]
I am running a local Azure Static Web Apps Functions emulator using [@azure/static-web-apps-cli@1.0.6](https://www.npmjs.com/package/@azure/static-web-apps-cli).

I am using the following Core Tools / Runtime version (i have upgraded to latest versions in an attempt to fix this issue):
`Azure Functions Core Tools`
`Core Tools Version:       4.0.4915 Commit hash: N/A  (64-bit)`
`Function Runtime Version: 4.14.0.19631`

I am using the following `extensionBundle` in `host.json`:
`"extensionBundle": {`
`    "id": "Microsoft.Azure.Functions.ExtensionBundle.Preview",`
`    "version": "[4.*, 5.0.0)"`
`}`

Supposedly, some upgrade of some package has caused every SQL function to return the following server error:

`System.Private.CoreLib: Exception while executing function: Functions.Test. Microsoft.Data.SqlClient: The type initializer for 'Microsoft.Data.SqlClient.SqlAuthenticationProviderManager' threw an exception. Microsoft.Data.SqlClient: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.`

I am not sure whether it cannot find the `System.Configuration.ConfigurationManager` file at all or if it cannot find the specific version (5.0.0.0) of this file.

I have been digging through the possible locations for the `System.Configuration.ConfigurationManager` file and have come up with:

- `...\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin`
- `...\user\.swa\core-tools\v4`

At both of the above locations the `System.Configuration.ConfigurationManager` file is version `4.700.19.56404`

The SQL extension is located at
`...\user\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle.Preview\4.4.0\bin`

Also, in the `4.4.0` folder in the `extensions.csproj` file the following line is present:
`<AzureFunctionsVersion>v3</AzureFunctionsVersion>`
Shouldn't this be set to version 4?

**Comment by lucyzhang929** [comment]
Hi @maersk96, thanks for filing this issue. We are currently working on this and will update you once there is a fix. 

One workaround is to copy the `System.Configuration.ConfigurationManager` dll to the `...\user\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle.Preview\4.4.0\bin` folder.

**Comment by Charles-Gagnon** [comment]
An easier and safer workaround is to revert back to the previous extension bundle, you can do this by specifying the bundle version as 

```json
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle.Preview",
    "version": "[4.*, 4.4.0)"
  }
```

**Comment by Charles-Gagnon** [comment]
Update : A new version of the bundle has been released (4.5.0) which rolls back the SQL extension to 0.1.483. So anyone who used the above workaround should be able to undo that change now and things should work as they did previously as long as you're using 4.5.0 of the bundle. 

I'll close this now since the immediate issue has been resolved.

**Comment by maersk96** [comment]
Thank you!
I will check if it works later.
A weird thing is. It stopped working on both my local and not-updated production server at once. Is the extension bundle automatically kept up to date within the specified version range?

**Comment by Charles-Gagnon** [comment]
Every time you start up the function host it will get the highest version that fits the declared range. So by specifying `"version": "[4.*, 5.0.0)"` it'll grab the latest 4.* version. So yes, it will "update" automatically in those cases. Generally, this is recommended to pick up the latest fixes and improvements.
