### ISSUE TITLE
Leases Tables are never cleaned up

### ISSUE THREAD

**Issue by Raylehnhoff** [Azure/azure-functions-sql-extension#681]
Hi all,

I have this running on an Azure Function app that's running inside an Azure Container Environment.

What I've noticed is that every deployment/config change will create a new `az_func.Leases_<id>_<id>` table, leaving the old ones in-tact. There doesn't ever seem to be a point that these dead tables get cleaned up.

Is there some guidance to prevent this from growing in an unbound way?

**Comment by Charles-Gagnon** [comment]
I renamed the issue to more clearly state the problem - let me know if you think that's incorrect!

Thanks for the feedback, the current design is that we don't clean them up because we want to be able to have function apps be restarted and pick up where they left off. But clearly there's cases where this isn't desirable as you noted - so we'll look into improvements here.

**Comment by Raylehnhoff** [comment]
> I renamed the issue to more clearly state the problem - let me know if you think that's incorrect!

The rename is fine -- I was just hoping I was doing something wrong in this instance so a question was warranted over a bug.

> Thanks for the feedback, the current design is that we don't clean them up because we want to be able to have function apps be restarted and pick up where they left off. But clearly there's cases where this isn't desirable as you noted - so we'll look into improvements here.

Yes, this makes perfect sense for those cases. I'm not sure if running this on an App Service Environment vs ACE would completely change the naming scheme, so it wouldn't create a new table.

I think a desirable outcome of the behavior is that if the `GlobalState` table sees a `LastSyncVersion` for a particular `UserTableID` that's quite far behind, it just assumes the worker is no longer up and cleans things up. I'm not sure what the implications of this would be, though, and obviously it's not my place to offer solutions to you all.

Thanks for taking this ticket on. I appreciate it!

**Comment by Raylehnhoff** [comment]
If anyone finds this thread and is looking for a manual way to clean these up until an officially supported solution is implemented, I have this script I put together.

This script is useful if you run your azure functions in a containerized environment (I run in Azure Container Environments), and the sql trigger is creating tons of `Leases` tables 

I do not recommend running this on some sort of timer - you want to run it in a VERY controlled manner, because if you have multiple workers they may be on different versions/catching up. Ideally you can run it after a deployment and a new set of workers have spun up.

This script is obviously destructive and requires the ability to delete and drop tables in the `az_func` schema. 

Use at your own peril ☠

This script will:

1. Fetch the highest `LastSyncVersion` and set it into `@biggestSync`
2. Open a cursor and 
    1. Drop every table whose version is smaller than `@biggestSync`
    2. Delete records out of `az_func.GlobalState` for those removed tables
3. Close & Deallocate the cursor

This script is:

1. Repeatable
2. Seemingly safe in my testing (I run it after an environment is fully deployed)



```tsql
DECLARE @biggestSync int = (SELECT MAX(LastSyncVersion) FROM az_func.GlobalState)
DECLARE @table_name NVARCHAR(MAX);
DECLARE @UserFunctionId char(16)
DECLARE @UserTableId int
DECLARE table_cursor CURSOR FOR

SELECT 'az_func.Leases_'+UserFunctionId+'_'+convert(varchar(100),UserTableID) as TABLE_NAME, UserFunctionID, UserTableID
FROM az_func.GlobalState
WHERE LastSyncVersion < @biggestSync

OPEN table_cursor;

FETCH NEXT FROM table_cursor INTO @table_name, @UserFunctionId, @UserTableId;

WHILE @@FETCH_STATUS = 0
BEGIN
    EXEC ('DROP TABLE IF EXISTS ' + @table_name);
    DELETE FROM az_func.GlobalState WHERE UserFunctionID = @UserFunctionId and UserTableID = @UserTableId
    FETCH NEXT FROM table_cursor INTO @table_name, @UserFunctionId, @UserTableId;
END;

CLOSE table_cursor;

DEALLOCATE table_cursor;
```

**Comment by Astral100** [comment]
Another way to go around this issue is to indicate consistent name of the lease table in the SQLTrigger parameters.
For example: `[SqlTrigger("table_name", connectionString, "Leases_<table_name>")`

**Comment by MaddyDev** [comment]
We added documentation on how to delete the unused tables, closing this now and we can reopen it when we have a better implementation.
