### ISSUE TITLE
Microsoft.Data.SqlClient: Keyword not supported: 'accountendpoint'

### ISSUE THREAD

**Issue by shashimahawaththa** [Azure/azure-functions-sql-extension#685]
Hello @lucyzhang929,

I was trying to get some data from my cosmoDB collection using @SQLInput and I have configured my data models and collection properly.
 
But when I was trying to execute the api, I'm getting below error,
![image](https://user-images.githubusercontent.com/39517229/219037829-53f5c796-c040-4a72-a115-552cf6d38357.png)

This is my local.settings.json
![image](https://user-images.githubusercontent.com/39517229/219038061-c5d40dcb-ec97-42ec-aea7-cc498b7e3f43.png)

This is my host.json
![image](https://user-images.githubusercontent.com/39517229/219038175-ef68452b-c0f3-40a0-a2ef-bd727a3181a6.png)

This is my Function App,
![image](https://user-images.githubusercontent.com/39517229/219038402-7ea95a9b-f36b-4975-9857-70ad9e2e8217.png)

**Comment by shashimahawaththa** [comment]
Hi @lucyzhang929 , could you please attend to this query too?

**Comment by Charles-Gagnon** [comment]
If you're getting data from a Cosmos DB instance you should likely be using the [CosmosDB Bindings](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2-input?tabs=in-process%2Cfunctionsv2&pivots=programming-language-python) - is there something preventing that from being an option?

If you could provide the connection string you're using as well that might help (with sensitive information like the server name removed) - the error seems to indicate that what you're passing isn't something SqlClient recognizes.

**Comment by shashimahawaththa** [comment]
Hi Charles,

Thanx for you response. Actually here I am trying to get data from 2 tables and trying to combine results, in that case CosmosDB Bindings is not supporting since I can use only one CosmoDB input binding at once, So that why I was trying to use this @SQLInput approach. here is my cosmoDB connection String,
"AzureCosmosDBConnection": "AccountEndpoint=https://cosmos-<project>.documents.azure.com:<PORT>/;AccountKey=###############################;",

**Comment by dzsquared** [comment]
@shashimahawaththa - CosmosDB isn't compatible with the Azure SQL bindings, which cover Azure SQL Database, Azure SQL Managed Instance, and SQL Server 2016+

Keep in mind you can add more than 1 input binding to a function, so you could put 2 CosmosDB input bindings on your function and assemble the collective results in the function

**Comment by Charles-Gagnon** [comment]
And if you have issues with getting that to work you can submit an issue in their repo : https://github.com/Azure/azure-webjobs-sdk-extensions
