### ISSUE TITLE
bump SqlClient to 3.0

### ISSUE THREAD

**Issue by dzsquared** [Azure/azure-functions-sql-extension#69]
https://github.com/dotnet/SqlClient/tree/main/release-notes/3.0

adds support for configurable retry and secure enclave

**Comment by chlafreniere** [comment]
@Charles-Gagnon, @lucyzhang929 FYI. Chatted with @dzsquared about this and we'd like to get this in before public preview for the reasons above. Happy to chat more when you're back.
