### ISSUE TITLE
Issue with column order in the sample project

### ISSUE THREAD

**Issue by JetterMcTedder** [Azure/azure-functions-sql-extension#690]
When deploying the sample project, and entering a value into the comments field and submitting it; seeing this error:

**[2023-02-20T23:48:36.702Z] Executed 'Functions.AddEntry' (Failed, Id=89433610-213f-4d90-a3cb-1a7976579014, Duration=535ms)
[2023-02-20T23:48:36.705Z] System.Private.CoreLib: Exception while executing function: Functions.AddEntry. Microsoft.Azure.WebJobs.Host: Error while handling parameter _binder after function returned:. Core Microsoft SqlClient Data Provider: Conversion failed when converting the nvarchar value 'my comment' to data type bit.**

Looking at the column order in this file

https://github.com/Azure-Samples/sql-bindings-guestbook/blob/main/apis/js-api/AddEntry/index.js

        newRow = {
            TextEntry: req.body.newEntry,
            DisableView: false,
            DateCreated: date.toISOString(),
            DateModerated: null
        };
 
 
I switched the TextEntry and the DisableView and the above error went away.
 
        newRow = {
            **DisableView: false,
            TextEntry: req.body.newEntry,**
            DateCreated: date.toISOString(),
            DateModerated: null
        };

I can only guess that the binding is column sensitive?

**Comment by Charles-Gagnon** [comment]
Am I correct in assuming that the table schema has the columns in the order of the second data blob? (DisableView followed by TextEntry)

**Comment by JetterMcTedder** [comment]
Correct:


```
CREATE TABLE [app].[Entry]
(
  [Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [DisableView] BIT NOT NULL DEFAULT(0),
  [TextEntry] NVARCHAR(MAX) NOT NULL,
  [DateCreated] DATETIME NOT NULL DEFAULT(GETDATE()),
  [DateModerated] DATETIME NULL
);
GO
```

**Comment by lucyzhang929** [comment]
@Charles-Gagnon I can take a look if you haven't already.

**Comment by Charles-Gagnon** [comment]
That would be great! Let me know if you need anything

**Comment by lucyzhang929** [comment]
@JetterMcTedder A new extension bundle version (v4.6.0) has been released with this fix. Your function should automatically pick up the latest version if you have the following in your host.json:
```
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle.Preview",
    "version": "[4.*, 5.0.0)"
  }
  ```
