### ISSUE TITLE
Investigate use of InstanceConcurrency for target based scaling

### ISSUE THREAD

**Issue by AmeyaRele** [Azure/azure-functions-sql-extension#696]
Issue opened to address comment by Charles on PR for introducing target based scaling.
https://github.com/Azure/azure-functions-sql-extension/pull/598#discussion_r1108906290

**Comment by AmeyaRele** [comment]
Dynamic concurrency relates to the 'target executions per instance' of the trigger as written in this section https://learn.microsoft.com/en-us/azure/azure-functions/functions-target-based-scaling?tabs=v5%2Ccsharp#dynamic-concurrency-support 
Therefore relating it to MaxChangesPerWorker in SQL extension makes sense. The scaling performance can be looked into for further investigation on it. 
@chiangvincent, please do add if you have anything else related to dynamic concurrency for target based scaling.

**Comment by Charles-Gagnon** [comment]
Discussed offline and verified that we are using the value correctly.
