### ISSUE TITLE
Deadlocks and Latency in the Output Binding

### ISSUE THREAD

**Issue by sophiatev** [Azure/azure-functions-sql-extension#7]
In the current implementation of the `SqlAsyncCollector`, the [method](https://github.com/Azure/azure-functions-sql-extension/blob/dev/src/SqlBinding/SqlAsyncCollector.cs#L92) that upserts the user-provided rows into the appropriate SQL table uses the Repeatable Read transaction level. The Repeatable Read and Serializable transaction levels both ensure that read locks are held throughout the entire transaction, which is functionality we need. The `UpsertRowsAsync` method first reads all of the data currently stored in the user table. It uses it to determine which of the user-specified rows is an insert (the primary key value doesn't currently exist in the user table), or an update (it does). After doing so, it then upserts the user-specified rows. Consider the following scenario that can occur if we do not hold read locks throughout the entire transaction:

1. Thread 1 acquires a shared read lock on the user table and reads all of the rows in.
2. Thread 2 also acquires a shared read lock on the user table and does the same.
3. Thread 1 releases its shared read lock.
4. Thread 2 releases its shared read lock, and then acquires a write lock. It upserts its set of rows into the user table. Suppose in the set of rows that it upserts, it inserts a row with a new primary key value. Thread 1's set of rows also contains this primary key value. However, because it did not exist in the user table at the time that thread 1 read the rows from the user table, thread 1 thinks this row is an insert, not an update.
5. After thread 2 commits its transaction and releases its write lock, thread 1 acquires a write lock. It attempts to upsert its rows, only to discover a primary key conflict when it tries to insert a row with a primary key that already exists in the user table.

This scenario can be avoided if the read lock is held throughout the entirety of the transaction. Then, thread 2 would not be able to acquire a write lock in step 4. However, doing so can lead to deadlocks:
1. Thread 1 acquires a shared read lock on the user table and reads all of the rows in.
2. Thread 2 also acquires a shared read lock on the user table and does the same.
3. Both threads try to upgrade their read lock to a write lock to perform the upsert, but are unable to do so because the other thread still holds a read lock. 

If we have a lot of concurrency, this scenario could be somewhat common. It's worth considering alternatives to the current design that are less deadlock-prone. 

Another issue with the current design is that it requires three trips to the database to perform the upsert. One [trip](https://github.com/Azure/azure-functions-sql-extension/blob/dev/src/SqlBinding/SqlAsyncCollector.cs#L105) fetches the schema of the user table, [another](https://github.com/Azure/azure-functions-sql-extension/blob/dev/src/SqlBinding/SqlAsyncCollector.cs#L109) fetches all of the data in the user table, and the [third](https://github.com/Azure/azure-functions-sql-extension/blob/dev/src/SqlBinding/SqlAsyncCollector.cs#L138) performs the upsert. Strangely enough, it doesn't seem possible to combine the first two trips into one. This is because it is necessary that the schema of the user table is added to the `newData` table, which contains the rows the user wants to upsert. The `originalData` table then clones the schema of `newData`, and is populated with the existing rows of the user table in the second trip. This order of operations is necessary for the `Merge` [call](https://github.com/Azure/azure-functions-sql-extension/blob/dev/src/SqlBinding/SqlAsyncCollector.cs#L112) to work correctly. 

It would be good to look at alternative ways to achieve upsert, perhaps by using the SQL MERGE command. However, this seems like it would require us to generate our own SQL commands - the advantage of using the `SqlDataReader` is that it does the command generation for us.

**Comment by Charles-Gagnon** [comment]
This might already be done? Investigate

**Comment by chlafreniere** [comment]
Re: the 3 connections, does the connection need to be closed/reopened for every query?

e.g.

https://github.com/Azure/azure-functions-sql-extension/blob/ad352485aad33a10d457d550fc80a0475d3a93fb/src/SqlBinding/SqlAsyncCollector.cs#L348

and then

https://github.com/Azure/azure-functions-sql-extension/blob/ad352485aad33a10d457d550fc80a0475d3a93fb/src/SqlBinding/SqlAsyncCollector.cs#L355

**Comment by lucyzhang929** [comment]
Closing since the SQL MERGE command is already implemented. https://github.com/Azure/azure-functions-sql-extension/issues/73 is tracking the connection lifecycle issues
