### ISSUE TITLE
Timeout Expired

### ISSUE THREAD

**Issue by jmarbutt** [Azure/azure-functions-sql-extension#709]
I am receiving this error on a SQL Azure Function Trigger. What would be causing this? 

```
 [Error]   Failed to release leases for table 'dbo.Customer' after 3 attempts due to exception:
Microsoft.Data.SqlClient.SqlException. 
Exception message: Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
```

**Comment by Charles-Gagnon** [comment]
Is this a consistent issue or just an occasional occurrence?

If you could set the default log level to Debug ([Instructions](https://learn.microsoft.com/en-us/azure/azure-functions/configure-monitoring?tabs=v2#configure-log-levels)), repro the issue and then attach the logs that would be helpful. These will contain object names such as database and table names - you can redact those first if you prefer.

**Comment by jmarbutt** [comment]
I will have to try again, I got so frustrated with it that I just went back to a `TimeTrigger` I will try again today.

**Comment by jmarbutt** [comment]
Is there a way to see what rows were impacted and waiting to be consumed by the SQL Trigger?

**Comment by Charles-Gagnon** [comment]
Not directly, but the debug logs will include what queries are being ran so you can see it yourself (or by using profiler/XEvents)

**Comment by jmarbutt** [comment]
What I am struggling with is sometimes in dev it isn't firing the trigger, not sure why. I am running out of ideas of how to find this. I have tried to increase the logs but I must be looking at the wrong place.

**Comment by jmarbutt** [comment]
I have my logs configured:
```
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingSettings": {
                "isEnabled": true
            }
        },
        "logLevel": {
            "default": "Information",
            "Host.Results": "Error",
            "Function": "Error",
            "Host.Aggregator": "Trace"
        }
    }
}
```

**Comment by jmarbutt** [comment]
Where I am seeing this not firing is when I edit the same DB row multiple times, it is like it ignores it, is there something I am doing wrong there?

**Comment by Charles-Gagnon** [comment]
Apologies, you should set the default to something higher than information otherwise it won't get anything more than the default (which is Information). The  instructions after this will show the settings you should have. 

You should be getting updates, even if the same row is being updated multiple times. But the error you were getting previously about the timeout expiring is definitely not expected and could cause the issues you're seeing (since it's not able to actually check for values).

**Comment by Charles-Gagnon** [comment]
Closing this for now until we can get more information. If you can get us those logs I'll reopen it and we can investigate further!
