### ISSUE TITLE
ntext, text, image SQL Data Types Not Supported

### ISSUE THREAD

**Issue by chlafreniere** [Azure/azure-functions-sql-extension#72]
When I tested these data types that [will be removed in the future](https://docs.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql?view=sql-server-ver15), I got the following error:

```
TEXT, NTEXT, SQL_VARIANT and IMAGE types cannot be used as column types in OPENJSON function with explicit schema.
```

We should document this in relnotes at a minimum.

**Comment by chlafreniere** [comment]
@dzsquared any thoughts on how to best accomplish this one?

**Comment by dzsquared** [comment]
by design, no deprecated types 🔥
