### ISSUE TITLE
Add Changelog File

### ISSUE THREAD

**Issue by chlafreniere** [Azure/azure-functions-sql-extension#80]
Consider having a checked in changelog file that can provide historical context for various releases.

Sample to consider following is here: https://github.com/dotnet/SqlClient/blob/main/CHANGELOG.md

**Comment by Charles-Gagnon** [comment]
Do we really need this? There's a lot of repos that don't use this (https://github.com/Azure/azure-webjobs-sdk and our own repos for example...) and generally I think we should just be using the releases section for putting release notes.

**Comment by chlafreniere** [comment]
This was an ask by KVH, since he really likes how sqlclient does this. Happy to chat some more about alternatives.
