### ISSUE TITLE
Add back in some diagnostic logging

### ISSUE THREAD

**Issue by Charles-Gagnon** [Azure/azure-functions-sql-extension#810]
I recently removed most of our debug logging, but it was brought up that we likely will want to have some amount of logging to indicate that the function is running smoothly for supportability purposes. 

EventHubs can be used as a sample for what kind of logging is useful to have : https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs

We can also add in a config variable that - when enabled - will log much more verbose information if needed.

**Comment by MaddyDev** [comment]
We should look into SqlClient verbose logging and follow that pattern.

**Comment by Charles-Gagnon** [comment]
See https://github.com/microsoft/sqltoolsservice/pull/1544 for how I did it in STS
