### ISSUE TITLE
Python SQL trigger Azure function has no responding to database change

### ISSUE THREAD

**Issue by charliecheng23** [Azure/azure-functions-sql-extension#816]
I am trying to use the https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-azure-sql-trigger?tabs=in-process%2Cportal&pivots=programming-language-python. It is working fine on my VS code on my desktop. But no polling only happens after I publish it to the Azure portal; There is no error in the monitor as well. 

Below is my app service plan:

OS: Linux
Location: Canada Central
Price: P1v2

**Comment by chlafreniere** [comment]
Hi @charliecheng23, sorry to hear that you're encountering an issue here. Thank you for trying out the Python SQL Trigger! We'll take a look here and see how we can improve the monitoring story. I believe @lucyzhang929 was able to repro similar behavior while in certain error conditions.

For this particular issue, we believe that cases where you wouldn't see errors in the monitor are related to issues where connectivity to the database cannot be successfully established at startup. Besides the connection string being missing as one possible culprit, another common case that we see is regarding the SqlClient driver setting the "Encrypt" property to true by default (some docs here: https://techcommunity.microsoft.com/t5/sql-server-blog/released-general-availability-of-microsoft-data-sqlclient-4-0/ba-p/2983346).

**Comment by charliecheng23** [comment]
Hi! Chris,

Thank you very much for your follow-up and support!
I also wrote an HTTP trigger function using pyodbc to test the connection, the connection seems fine.
I set the Encrypt=False in the connection string and redeploy the function app. 
It still has no luck so far, no function id is being created at az_func.GlobalState table and not az_func.functionid_usertableid being created in Azure sql MI database

I noticed the below log in the publish log:
7:30:51 PM AER-GisServicePOC-DEV-FUNC-01: Triggering recycle (preview mode disabled).
7:30:52 PM AER-GisServicePOC-DEV-FUNC-01: Deployment successful. deployer = ms-azuretools-vscode deploymentPath = Functions App ZipDeploy. Extract zip. Remote build.
7:31:14 PM AER-GisServicePOC-DEV-FUNC-01: Syncing triggers...
7:31:18 PM AER-GisServicePOC-DEV-FUNC-01: Querying triggers...

Does it mean the preview function is not available?

**Comment by charliecheng23** [comment]
Hi! Chris,

I also tried to create a python SQL binding function under the same function app.

It did  return the following errors:

The remote certificate was rejected by the provided RemoteCertificateValidationCallback.

It sounds like a connection issue between the function app and Azure SQL database MI 

Any idea how to fix it?  

Thanks a lot

**Comment by chlafreniere** [comment]
@dzsquared Is this a case where TrustServerCertificate needs to be set to true, or is this something else? Not the expert here, unfortunately 😞

**Comment by Charles-Gagnon** [comment]
@charliecheng23 What type of auth are you using?

**Comment by charliecheng23** [comment]
@chlafreniere: Yes, you are right. I set both TrustServerCertificate=True, the SQL binding function is working now, but the SQL trigger is still not working. I am using the sql account

**Comment by Charles-Gagnon** [comment]
You have the same connection string for both? No typos or anything that would make them different? And you made sure to restart the app after making the change? 

And just to check - you're using the public endpoint for your MI server right?

**Comment by chlafreniere** [comment]
One other question too (building upon @Charles-Gagnon's answer) Have you setup Application Insights with your function? We should be outputting information both to the traces and exceptions tables. We do see information there in our own sample functions on our side.

**Comment by charliecheng23** [comment]
Yes. Sql binding and SQL trigger are in the same function app and use the same SQL connection string.
 I believe that we are using the private link endpoint, Azure function and Azure SQL MI in the different Vnet and subscriptions of our company
@chlafreniere : I do setup Application insights.  Do you mind sending me your sample query to traces and exception tables? thanks

**Comment by chlafreniere** [comment]
Absolutely. I haven't been doing anything fancy, but the innermostMessage column is more often than not the most helpful:

```
exceptions
| where cloud_RoleName == <app name>
| project timestamp, outerMessage, innermostMessage, problemId
```

**Comment by charliecheng23** [comment]
@chlafreniere : Below is the error in the exceptions table - ****The specified schema name "az_func" either does not exist or you do not have permission to use it..** Turn off the root cause was as follows:

1. My VS code function created the az_func schema and GlobalState table under my developer account
2. I grant the create table permission to the SQL account, then test it in VS Code, all work then deployed it to the portal
3. When the new function starts at the portal, it will need to access existing az_func schema tables in the database

I let DBA grant alter permission to existing az_func schema tables to the SQL account, SQL trigger function is working now

Thank you very much for your help!

**Comment by Charles-Gagnon** [comment]
Ahhh, yeah that'd do it. We'll see what we can do about surfacing the error better or at least documenting stuff like as things to look at. 

Did you ever figure out what was going on with the cert error you were seeing? The schema creation issue should have been independent of that.

**Comment by charliecheng23** [comment]
Changed to TrustServerCertificate=True  fixed the cert error - T**he remote certificate was rejected by the provided RemoteCertificateValidationCallback.**

**Comment by lucyzhang929** [comment]
Closing this since the issue has been resolved. @charliecheng23 please feel free to reopen or open a new issue if you have any other questions.

**Comment by charliecheng23** [comment]
Hi! Lucy:  SQL trigger Azure python function is very cool, can you let us know the release plan for SQL trigger Azure function python? thanks

**Comment by dzsquared** [comment]
@charliecheng23 - the SQL trigger for Python is available in public preview right now and will GA in the months following the GA of the input and output bindings (which will be very soon). I'm glad you're finding the Python trigger useful! What sort of events are you watching for?

**Comment by charliecheng23** [comment]
@dzsquared: Thank you, Drew! We are planning to use the Azure Python function SQL trigger to listen to the database table's insert and update event and trigger to process the updated record in real-time.

Our architects are concerned about the preview version as it may be subject to changes or cancellation at any time. Therefore, we would greatly appreciate it if you could provide confirmation that this function will be on the roadmap to GA and, if possible, an estimated timeline.

Thank you for your assistance
