### ISSUE TITLE
Returning custom HTTP Response when error happens in SQL Binding .NET (IsolatedProcess)

### ISSUE THREAD

**Issue by alacho22** [Azure/azure-functions-sql-extension#857]
## General Question
When errors happen in SQL Bindings for .NET isolated worker functions we want to be able to catch them in middleware and return a custom HTTP response. However, any errors in the SQL Input bindings seem to happen before the middleware is called. This means that, as far as we can tell, any `SqlException`s which occur (for example, when an API user provides an invalid value for the type being compared to in a WHERE clause) this will always result in a 500 error. Is there any way to avoid this without having to use the SDKs, rather than bindings?

### Requirement
We have an Azure SQL table named `Job` with an `Id` column of type `GUID `. We want to be able to create a simple C# HTTP Trigger which:
- Takes the `Id` as a URL parameter.
- If a Job with the specified `Id` exists, look it up and return it, in JSON format, in the body.
- If it doesn't then return a Not Found/404 response saying that the Job doesn't exist.

### Existing Solution
```
 public static async Task<HttpResponseData> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", Route = "job/{jobId}")]
            HttpRequestData req,
            Guid jobId,
            [SqlInput(
                "select * from dbo.Job where Id = @Id",
                "SqlConnectionString",
                parameters: "@Id={jobId}")] IEnumerable<Job> jobSingleton)
        {
        if (job == null) {
          // return 404 response
        }
        // return 200 response with job as JSON body
}
```

### What isn't working
If the provided `Id` URL parameter isn't a valid GUID then a `SqlException` is thrown saying that "Conversion failed when converting from a character string to uniqueidentifier." We would like to be able to catch this exception in middleware and return a 404 response there.

### Temporary fix
Luckily for this issue, we are able to change the column type to string as we don't have any meaningful data in there yet. However, I think this is likely to be an issue that we will run into again at some point as we really don't want to be exposing 500 errors to our API users.

**Comment by Charles-Gagnon** [comment]
You could try using [imperative binding](https://learn.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v4%2Ccmd#binding-at-runtime) to declare and execute the binding at runtime. This would let you validate input and catch any errors coming from the binding, then return a custom HTTP response as needed.

**Comment by alacho22** [comment]
@MaddyDev thanks for your response. Yes, you're right I wouldn't expect the SQL binding itself to return a 404, however, I would expect to have the ability to catch that error in middleware and handle it as we see fit. In our case when the user sends a request to `job/{jobId}` we should return a 404 as the resource they requested (the job with the specified id) doesn't exist.

**Comment by alacho22** [comment]
Thanks @Charles-Gagnon that does look like it would work, but it would be much nicer to be able to still use the declarative bindings and just have a sensible mechanism for handling errors. This is what I would expect the middleware to be able to handle. I think this is likely to become more of a problem as people start to migrate to .NET isolated workers.

**Comment by Charles-Gagnon** [comment]
@dzsquared @fabiocav Do you know of any way to accomplish what is being asked here without using imperative bindings?

@alacho22 I briefly looked around and it seems like there might be some middleware support for modifying the HttpResponse - see https://github.com/Azure/azure-functions-dotnet-worker/issues/414 and https://github.com/Azure/azure-functions-dotnet-worker/issues/340 for details

**Comment by dzsquared** [comment]
Here's a sample with imperative bindings that returns a bad request if the SQL binding throws an exception. A similar structure can be used to try-parse the ID ahead of the SQL binding.

```csharp
[FunctionName("GetUserInfo")]
public static async Task<IActionResult> Run(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "userinfo")] HttpRequest req,
    IBinder binder,
    ILogger log)
{
    // get UserId and Passkey from header
    Guid userId = Guid.Parse(req.Headers["x-tag-userid"]);
    Guid passkey = Guid.Parse(req.Headers["x-tag-passkey"]);

    try
    {
        var sqlAttribute = new SqlAttribute(connectionStringSetting: "SqlConnectionString",
            commandText: "[Tag].[GetUserInfo]",
            commandType: System.Data.CommandType.StoredProcedure,
            parameters: $"@UserIdInput={userId},@PasskeyInput={passkey}"
        );

        // get user info from database
        var userInfoList = await binder.BindAsync<IEnumerable<UserInfo>>(sqlAttribute);
        UserInfo userInfo = userInfoList.FirstOrDefault();

        return new OkObjectResult(userInfo);
    }
    catch (Exception ex)
    {
        log.LogError(ex.Message);
        return new BadRequestObjectResult(ex.Message);
    }
}
```

https://github.com/Azure-Samples/azure-sql-blazor-tag-game-sample/blob/main/APIs/GetUserInfo.cs


I understand the hope that middleware handles as much as possible, and imperative bindings are that middle ground where the nice wrapping on connection handling and results is maintained but finer control over pre/post execution is available.
