### ISSUE TITLE
Invalid operation: the connection has been broken.

### ISSUE THREAD

**Issue by marthijn** [Azure/azure-functions-sql-extension#860]
I see a similar problem as #723 for the SQL Trigger.
Instead of a closed connection, now the connection has been broken. It occurred after a few month since upgrading to version **3.0.143-preview**. Restarting the function app solved the problem.
I'm currently updating my solution to the latest version. I'll let you know if the problem still occurs.

See the logs below, ordered by timestamp desc. The first occurrence is at 5/23/2023, 8:09:01.577

|Timestamp|Message                      |severityLevel|itemType                                     |
|---------|-----------------------------|-------------|---------------------------------------------|
|5/23/2023, 8:09:25.729 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:25.729 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:25.729 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:25.729 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:09:25.729 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:24.738 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:09:24.738 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:24.738 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:24.738 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:24.738 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:09:24.738 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:24.554 PM|TID:6 ReleaseRowsLock - RenewLeases|0            |trace                                        |
|5/23/2023, 8:09:24.554 PM|TID:6 END WaitRowsLock - RenewLeases|0            |trace                                        |
|5/23/2023, 8:09:24.554 PM|TID:6 BEGIN WaitRowsLock - RenewLeases|0            |trace                                        |
|5/23/2023, 8:09:23.723 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:09:23.723 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:23.723 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:23.723 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:23.723 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:09:23.722 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:22.708 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:09:22.708 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:22.708 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:22.707 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:22.707 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:09:22.707 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:21.697 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:09:21.697 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:21.697 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:21.697 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:21.697 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:09:21.697 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:21.212 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync start. MessageCount = 1|1            |trace                                        |
|5/23/2023, 8:09:21.212 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync done. Received '0' messages. LockTokens =|1            |trace                                        |
|5/23/2023, 8:09:20.694 PM|TID:29 Delaying for 1000ms   |0            |trace                                        |
|5/23/2023, 8:09:20.694 PM|TID:29 END ProcessingChanges |0            |trace                                        |
|5/23/2023, 8:09:20.694 PM|TID:29 END GetTableChanges   |0            |trace                                        |
|5/23/2023, 8:09:20.694 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:20.694 PM|TID:29 BEGIN GetTableChanges |0            |trace                                        |
|5/23/2023, 8:09:20.694 PM|TID:29 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:19.686 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:09:19.685 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:19.685 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:19.685 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:19.685 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:09:19.685 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:18.680 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:09:18.680 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:18.680 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:18.680 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:18.680 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:09:18.680 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:17.676 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:09:17.676 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:17.675 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:17.675 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:17.675 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:09:17.675 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:16.672 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:09:16.672 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:16.672 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:16.672 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:16.672 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:09:16.671 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:15.656 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:09:15.656 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:15.656 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:15.656 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:15.656 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:09:15.656 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:14.653 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:09:14.653 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:14.653 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:14.652 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:14.652 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:09:14.652 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:13.650 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:09:13.650 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:13.650 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:13.650 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:13.650 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:09:13.649 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:12.654 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:09:12.654 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:12.654 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:12.654 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:12.654 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:09:12.654 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:11.636 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:09:11.636 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:11.636 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:11.636 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:11.636 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:09:11.636 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:10.635 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:09:10.635 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:10.635 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:10.635 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:10.635 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:09:10.635 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:09.633 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:09:09.633 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:09.633 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:09.633 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:09.633 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:09:09.633 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:09.539 PM|TID:6 ReleaseRowsLock - RenewLeases|0            |trace                                        |
|5/23/2023, 8:09:09.539 PM|TID:6 END WaitRowsLock - RenewLeases|0            |trace                                        |
|5/23/2023, 8:09:09.539 PM|TID:6 BEGIN WaitRowsLock - RenewLeases|0            |trace                                        |
|5/23/2023, 8:09:08.625 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:09:08.625 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:08.625 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:08.625 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:08.625 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:09:08.625 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:07.617 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:09:07.617 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:07.617 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:07.617 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:07.616 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:09:07.616 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:06.613 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:09:06.613 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:06.613 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:06.613 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:06.612 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:09:06.612 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:06.105 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync start. MessageCount = 1|1            |trace                                        |
|5/23/2023, 8:09:06.105 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync done. Received '0' messages. LockTokens =|1            |trace                                        |
|5/23/2023, 8:09:05.600 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:09:05.600 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:05.600 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:05.600 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:05.599 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:09:05.599 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:04.590 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:09:04.590 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:04.590 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:04.590 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:04.589 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:09:04.589 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:03.585 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:09:03.585 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:03.585 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:03.585 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:03.585 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:09:03.585 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:02.578 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:09:02.578 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:02.578 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:02.577 PM|Failed to check for changes in table 'MY-TABLE' due to exception: System.InvalidOperationException. Exception message: The requested operation cannot be completed because the connection has been broken.|3            |trace                                        |
|5/23/2023, 8:09:02.575 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:09:02.574 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:09:01.580 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:09:01.580 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:09:01.580 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:09:01.577 PM|**Failed to check for changes in table 'MY-TABLE' due to exception: Microsoft.Data.SqlClient.SqlException. Exception message: The connection is broken and recovery is not possible.  The client driver attempted to recover the connection one or more times and all attempts failed.  Increase the value of ConnectRetryCount to increase the number of recovery attempts.**|3            |trace                                        |
|5/23/2023, 8:08:54.842 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync start. MessageCount = 1|1            |trace                                        |
|5/23/2023, 8:08:54.842 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync done. Received '0' messages. LockTokens =|1            |trace                                        |
|5/23/2023, 8:08:54.531 PM|TID:39 ReleaseRowsLock - RenewLeases|0            |trace                                        |
|5/23/2023, 8:08:54.531 PM|TID:39 END WaitRowsLock - RenewLeases|0            |trace                                        |
|5/23/2023, 8:08:54.531 PM|TID:39 BEGIN WaitRowsLock - RenewLeases|0            |trace                                        |
|5/23/2023, 8:08:45.409 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync start. MessageCount = 1|1            |trace                                        |
|5/23/2023, 8:08:45.408 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync done. Received '0' messages. LockTokens =|1            |trace                                        |
|5/23/2023, 8:08:41.725 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync start. MessageCount = 1|1            |trace                                        |
|5/23/2023, 8:08:41.724 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync done. Received '0' messages. LockTokens =|1            |trace                                        |
|5/23/2023, 8:08:41.240 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync start. MessageCount = 1|1            |trace                                        |
|5/23/2023, 8:08:41.240 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync done. Received '0' messages. LockTokens =|1            |trace                                        |
|5/23/2023, 8:08:41.239 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync start. MessageCount = 1|1            |trace                                        |
|5/23/2023, 8:08:41.239 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync done. Received '0' messages. LockTokens =|1            |trace                                        |
|5/23/2023, 8:08:41.239 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync start. MessageCount = 1|1            |trace                                        |
|5/23/2023, 8:08:41.239 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync done. Received '0' messages. LockTokens =|1            |trace                                        |
|5/23/2023, 8:08:41.239 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync start. MessageCount = 1|1            |trace                                        |
|5/23/2023, 8:08:41.239 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync done. Received '0' messages. LockTokens =|1            |trace                                        |
|5/23/2023, 8:08:41.239 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync start. MessageCount = 1|1            |trace                                        |
|5/23/2023, 8:08:41.239 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync done. Received '0' messages. LockTokens =|1            |trace                                        |
|5/23/2023, 8:08:41.239 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync start. MessageCount = 1|1            |trace                                        |
|5/23/2023, 8:08:41.239 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync done. Received '0' messages. LockTokens =|1            |trace                                        |
|5/23/2023, 8:08:41.238 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync start. MessageCount = 1|1            |trace                                        |
|5/23/2023, 8:08:41.238 PM|servicebuscommand-730be7a3-873f-496a-9a07-b60f06c1b727-Receiver: ReceiveBatchAsync done. Received '0' messages. LockTokens =|1            |trace                                        |
|5/23/2023, 8:08:40.540 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:08:40.540 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:08:39.528 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:08:39.528 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:08:39.528 PM|TID:6 END ProcessTableChanges|0            |trace                                        |
|5/23/2023, 8:08:39.528 PM|TID:6 ReleaseRowsLock - ClearRows|0            |trace                                        |
|5/23/2023, 8:08:39.528 PM|TID:6 END WaitRowsLock - ClearRows|0            |trace                                        |
|5/23/2023, 8:08:39.528 PM|TID:6 BEGIN WaitRowsLock - ClearRows|0            |trace                                        |
|5/23/2023, 8:08:39.528 PM|TID:6 BEGIN ProcessTableChanges|0            |trace                                        |
|5/23/2023, 8:08:39.528 PM|TID:6 END GetTableChanges    |0            |trace                                        |
|5/23/2023, 8:08:39.526 PM|TID:29 ReleaseRowsLock - RenewLeases|0            |trace                                        |
|5/23/2023, 8:08:39.526 PM|TID:29 END WaitRowsLock - RenewLeases|0            |trace                                        |
|5/23/2023, 8:08:39.526 PM|TID:29 BEGIN WaitRowsLock - RenewLeases|0            |trace                                        |
|5/23/2023, 8:08:39.501 PM|TID:6 END GetChanges Duration=1ms ChangedRows=0|0            |trace                                        |
|5/23/2023, 8:08:39.499 PM|TID:6 BEGIN GetChanges Query=                 DECLARE @result int;                 EXEC @result = sp_getapplock @Resource = '_az_func_Trigger',                             @LockMode = 'Exclusive',                             @LockTimeout = 30000                 IF @result < 0                 BEGIN                     RAISERROR('Unable to acquire exclusive lock on _az_func_Trigger. Result = %d', 16, 1, @result)                 END;                  DECLARE @last_sync_version bigint;                 SELECT @last_sync_version = LastSyncVersion                 FROM [az_func].[GlobalState]                 WHERE UserFunctionID = '005aa3cea0ccb2cc' AND UserTableID = 978102525;                  SELECT TOP 100                     c.[id], u.**REDACTED**,                     c.SYS_CHANGE_VERSION,                     c.SYS_CHANGE_OPERATION,                     l._az_func_ChangeVersion,                     l._az_func_AttemptCount,                     l._az_func_LeaseExpirationTime                 FROM CHANGETABLE(CHANGES [MY-TABLE], @last_sync_version) AS c                 LEFT OUTER JOIN [az_func].[Leases_005aa3cea0ccb2cc_978102525] AS l ON c.[id] = l.[id]                 LEFT OUTER JOIN [MY-TABLE] AS u ON c.[id] = u.[id]                 WHERE                     (l._az_func_LeaseExpirationTime IS NULL AND                        (l._az_func_ChangeVersion IS NULL OR l._az_func_ChangeVersion < c.SYS_CHANGE_VERSION) OR                         l._az_func_LeaseExpirationTime < SYSDATETIME()                     ) AND                     (l._az_func_AttemptCount IS NULL OR l._az_func_AttemptCount < 5)                 ORDER BY c.SYS_CHANGE_VERSION ASC;|0            |trace                                        |
|5/23/2023, 8:08:39.499 PM|TID:6 END UpdateTablesPreInvocation Duration=2ms|0            |trace                                        |
|5/23/2023, 8:08:39.497 PM|TID:6 BEGIN UpdateTablesPreInvocation Query=                 DECLARE @result int;                 EXEC @result = sp_getapplock @Resource = '_az_func_Trigger',                             @LockMode = 'Exclusive',                             @LockTimeout = 30000                 IF @result < 0                 BEGIN                     RAISERROR('Unable to acquire exclusive lock on _az_func_Trigger. Result = %d', 16, 1, @result)                 END;                  DECLARE @min_valid_version bigint;                 SET @min_valid_version = CHANGE_TRACKING_MIN_VALID_VERSION(978102525);                  DECLARE @last_sync_version bigint;                 SELECT @last_sync_version = LastSyncVersion                 FROM [az_func].[GlobalState]                 WHERE UserFunctionID = '005aa3cea0ccb2cc' AND UserTableID = 978102525;                  IF @last_sync_version < @min_valid_version                     UPDATE [az_func].[GlobalState]                     SET LastSyncVersion = @min_valid_version                     WHERE UserFunctionID = '005aa3cea0ccb2cc' AND UserTableID = 978102525;|0            |trace                                        |
|5/23/2023, 8:08:39.495 PM|TID:6 BEGIN GetTableChanges  |0            |trace                                        |
|5/23/2023, 8:08:39.494 PM|TID:6 BEGIN ProcessingChanges State=CheckingForChanges|0            |trace                                        |
|5/23/2023, 8:08:38.493 PM|TID:6 Delaying for 1000ms    |0            |trace                                        |
|5/23/2023, 8:08:38.493 PM|TID:6 END ProcessingChanges  |0            |trace                                        |
|5/23/2023, 8:08:38.493 PM|TID:6 END ProcessTableChanges|0            |trace                                        |
|5/23/2023, 8:08:38.493 PM|TID:6 ReleaseRowsLock - ClearRows|0            |trace                                        |
|5/23/2023, 8:08:38.493 PM|TID:6 END WaitRowsLock - ClearRows|0            |trace                                        |
|5/23/2023, 8:08:38.493 PM|TID:6 BEGIN WaitRowsLock - ClearRows|0            |trace                                        |
|5/23/2023, 8:08:38.493 PM|TID:6 BEGIN ProcessTableChanges|0            |trace                                        |

**Comment by Charles-Gagnon** [comment]
@marthijn This is probably because of https://github.com/dotnet/SqlClient/issues/1874

Is this a .NET function? If so could you try updating to the [5.2.0-preview1.23109.1](https://www.nuget.org/packages/Microsoft.Data.SqlClient/5.2.0-preview1.23109.1) version of the SqlClient package and see if that seems to fix it?

**Comment by marthijn** [comment]
@Charles-Gagnon This is a .NET function indeed. I'll update the SqlClient package. The problem is that the fix is not easy to validate, since the problem occurred after two months on only one of our environments.

**Comment by Charles-Gagnon** [comment]
@marthijn We just released a new version of the extension with the temporary fix that should address the issue in the short term. Let us know if you still continue to see failures after updating!

https://github.com/Azure/azure-functions-sql-extension/releases/tag/v3.0.253-preview

**Comment by marthijn** [comment]
Thanks @Charles-Gagnon , I'll let you know.
