### ISSUE TITLE
Investigate Targeting .NET 6.0

### ISSUE THREAD

**Issue by chlafreniere** [Azure/azure-functions-sql-extension#88]
Currently, projects are targeting netcorestandard2.1. Would be interesting to investigate whether we can easily move to .NET 6.0

**Comment by Charles-Gagnon** [comment]
Question to consider as well - should we be targeting multiple frameworks to support the older runtimes as well? Should look at other bindings to see what they do.

**Comment by soninaren** [comment]
> Question to consider as well - should we be targeting multiple frameworks to support the older runtimes as well? Should look at other bindings to see what they do.

At this point you would be required to target multiple frameworks to be able to support function runtime v3.

**Comment by Charles-Gagnon** [comment]
Not planning on changing this now - functions can target the framework as needed but the base extension will stay as netstandard2.0 to be compatible with the other extensions in the bundle.
