### ISSUE TITLE
MultiHostTriggerTest(lang: Java) Test Timeouts

### ISSUE THREAD

**Issue by chlafreniere** [Azure/azure-functions-sql-extension#912]
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=210462&view=ms.vss-test-web.build-test-results-tab&runId=2646124&resultId=100324&paneView=debug

**Comment by VasuBhog** [comment]
This seems to be similar to https://github.com/Azure/azure-functions-sql-extension/issues/905.

**Comment by Charles-Gagnon** [comment]
Added to wiki, will track there.
