### ISSUE TITLE
How to insert foreign key using auto generated identity columns in Azure Functions using SQL OutputBinding in isolated model?

### ISSUE THREAD

**Issue by nyghtrocker** [Azure/azure-functions-sql-extension#928]
I am trying to use the SQL OutputBinding attribute in Azure Functions (isolated process model) to insert data into two related tables in Azure SQL database. The tables are Invoice and InvoiceLineItem, and they have a one-to-many relationship. The Invoice table has an identity column (InvoiceId) that is the primary key, and the InvoiceLineItem table has a foreign key column (InvoiceId) that references the Invoice table. I want to insert data into both tables using the SQL OutputBinding attribute, but I don't know how to get the auto-generated identity value from the Invoice table and use it as the foreign key value for the InvoiceLineItem table. Here is the C# code for the classes that represent the tables:

`public class Invoice
{
public long InvoiceId { get; set; }

public int? InvoiceClientId { get; set; }

public string CurrencyCode { get; set; }

public ICollection<InvoiceLineItem> LineItem { get; set; }

}

public class InvoiceLineItem
{
public long InvoiceLineItemId { get; set; }

public long? InvoiceId { get; set; }

public int? Hours { get; set; }

public double? RatePerHours { get; set; }

public string WorkDescriptions { get; set; }

}
`

How can I use the SQL OutputBinding attribute to insert data into both tables and use the auto-generated identity value from the Invoice table as the foreign key value for the InvoiceLineItem table? Can anyone provide a demo or an example of how to do this? Thank you.

**Comment by lucyzhang929** [comment]
Hi @nyghtrocker, unfortunately there is no way to return auto-generated values from a SQL Output Binding. You can try using two functions:
- one function with a SQL Output Binding to insert values into Invoice
- and a second function with a SQL Input Binding to get the InvoiceId from Invoice and a SQL Output Binding to insert values into InvoiceLineItem

**Comment by lucyzhang929** [comment]
Closing this issue since there is no way to get values return from output bindings. @nyghtrocker Feel free to open an issue in the [Azure Functions Host repo](https://github.com/Azure/azure-functions-host/issues) if this is functionality you'd like to see.
