### ISSUE TITLE
Learn docs link to extension bundle for preview package functionality

### ISSUE THREAD

**Issue by Charles-Gagnon** [Azure/azure-functions-sql-extension#985]
https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-azure-sql?tabs=isolated-process%2Cextensionv4&pivots=programming-language-csharp

In here we link to the extension bundle release page for preview functionality

![image](https://github.com/Azure/azure-functions-sql-extension/assets/28519865/ab80eecd-ffb4-40ec-ae9f-8ffcf756d188)

But that page doesn't have any info on preview functionality for our package itself. It would probably be better to link to our releases page instead.

**Comment by MaddyDev** [comment]
Closing this since Brian updated it as done.
